### ISSUE TITLE
Documenting the API with sphinx and readthedocs

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#108]
Let's set up a bare API reference with Sphinx via Read the Docs (RtD) at https://orix.readthedocs.io, as is done by e.g. HyperSpy (https://github.com/hyperspy/hyperspy/tree/RELEASE_next_minor/doc) and kikuchipy (https://github.com/kikuchipy/kikuchipy/tree/master/doc).

I'm fine with setting this up after v0.4.0 is out the door.

This requires
1. readthedocs.yml config file in the top directory
2. a orix/doc/ directory with make files (Makefile and make.bat), .rst files (index.rst and reference.rst/api.rst at a minimum) and a _static/ directory with any images, favicons etc.
3. someone with admin access to this repo sets up a GitHub webhook to RtD (https://docs.readthedocs.io/en/latest/webhooks.html#github). (It seems I don't have that yet.) 
4. now merges into specified branches/tags (like master and some older v0.3.x for example) will prompt RtD to rebuild the docs!

We will need to update docstring parameters, links to other packages (so-called intersphinx), examples etc. for everything to look nice and linked correctly. We can do this before pushing the RtD doc stuff by building the docs locally (https://docs.readthedocs.io/en/latest/intro/getting-started-with-sphinx.html#quick-start).

* I also think we should add a `doc` extra feature requirements in setup.py with `sphinx`, `sphinx-rtd-theme` (if we use that theme) and other sphinx related packages, that can be used as `pip install --editable .[doc]` to install doc related dependencies. This way people can build the docs locally themselves if they want to.

* I suggest the standard RtD Sphinx theme (https://docs.readthedocs.io), however there are many others shown here (https://sphinx-themes.org/) and elsewhere. I guess the pyxem website uses the sphinx-bootstrap theme.

* We can tell RtD to build a PDF of the API as well (even an epub file!).

* Note that since RtD will be hosting the docs, https://orix.readthedocs.io will have a small ad at the bottom of the side bar.

**Comment by hakonanes** [comment]
Also adding a "docs passing" badge to the readme is nice.

**Comment by dnjohnstone** [comment]
I think the plan here is pretty clear and we all agree on it, so marking as 0.5.0

**Comment by hakonanes** [comment]
The documentation needs improvement: intersphinx links in docstrings and more examples, at least. But that can be added later on.
