### ISSUE TITLE
Improve adding a Phase to a PhaseList

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#109]
Adding a `orix.crystal_map.Phase` to a `orix.crystal_map.PhaseList` is currently done like so

```python
>>> from orix.crystal_map import Phase, PhaseList
>>> pl = PhaseList(names=["a", "b"], space_group=[10, 20])
>>> pl
Id  Name  Space group  Point group  Proper point group       Color
 0     a         P2/m          2/m                 112    tab:blue
 1     b        C2221          222                 222  tab:orange
>>> pl["c"] = "m-3m"
>>> pl
Id  Name  Space group  Point group  Proper point group       Color
 0     a         P2/m          2/m                 112    tab:blue
 1     b        C2221          222                 222  tab:orange
 2     c         None         m-3m                 432   tab:green
```

I didn't think this that much through upon implementing the `PhaseList.__setitem__()` method, as now I would have to set the space group in another line...

I think removing this `__setitem__()` method and adding a `PhaseList.append(Phase())` method is better.

**Comment by dnjohnstone** [comment]
Yeah, I think I agree that a `PhaseList.append()` method would be better.
