### ISSUE TITLE
Vector3d class should have radius and polar coordinates as attributes

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#115]
MTEX' `Vector3d` has these properties (https://github.com/mtex-toolbox/mtex/blob/develop/geometry/%40vector3d/vector3d.m#L47), we should too.

I just found myself wanting the spherical coordinates of `Vector3d`, i.e. the radius r = sqrt(x**2 + y**2 + z**2), polar coordinate theta = atan2(y, x) and azimuthal coordinate phi/rho =  arccos(z / r). The computations are simple, so I think these should be attributes of `Vector3d` computed on the fly.

Will make a PR shortly if there is agreement.

**Comment by pc494** [comment]
`to_polar`? With a fairly clear description of convention and a test that runs it against `from_polar`? Sounds great!

**Comment by dnjohnstone** [comment]
Inevitably we're going to end up talking about how this should play with `pyxem.DiffractionVectors` before too long...

**Comment by hakonanes** [comment]
> `to_polar`? With a fairly clear description of convention and a test that runs it against `from_polar`? Sounds great!

Okay, so not have them accessible via `Vector3d.r`, `Vector3d.phi` etc? Basically

```python
def to_polar(self):
    """Convert from cartesian to spherical coordinates."""
    # Radius
    r = np.sqrt(self.x.data ** 2 + self.y.data ** 2 + self.z.data ** 2)
    # Azimuthal angle
    phi = np.atan2(self.y.data / self.x.data)
    phi += (phi < 0) * 2 * np.pi
    # Polar angle
    theta = np.arccos(self.z.data / r)
    return theta, rho, r
```

**Comment by pc494** [comment]
Nope, `Vectord3d.r` and `Vector3d.phi` is good; would be tempted to wrap those into a `to_polar` function as well
