### ISSUE TITLE
Release 0.1.1

### ISSUE THREAD

**Issue by dnjohnstone** [pyxem/orix#12]
Because error checking skills always improve by an order of magnitude after pressing submit....

We should:

- [x] update setup.py so license says GPL-3
- [x] update setup.py more generally to include a "long_description" link to readme and classifiers
- [x] decide on and implement branch structuring of main repo
- [x] check for any other silly mistakes
- [x] sort zenodo doi etc
- [x] conda release

**Comment by pc494** [comment]
In terms of branch structuring, the short term I think the inverse of what we use on the main repo is the way to go, master become `0.1.2dev` and a `0.2.x` branch is created. This helps keeping the cleaner code front facing, as `0.2.0` is likely to be quite different, and bumping master is likely to create problems (eg with the `gh-pages` branch).

**Comment by dnjohnstone** [comment]
I've done the zenodo do, should be auto created on our next github release!

**Comment by dnjohnstone** [comment]
Do you think we might be ok just working with a master branch for now. I think we anticipate relatively slow development in the short/medium term...

**Comment by pc494** [comment]
> Do you think we might be ok just working with a master branch for now. I think we anticipate relatively slow development in the short/medium term...

Yep, can do. Will think about a sensible way of working to keep the master pretty clean.

**Comment by dnjohnstone** [comment]
Ok, all done now I think, just waiting for a merge into conda-forge
