### ISSUE TITLE
RuntimeWarning: divide by zero... calling `OrientationRegion.get_plot_data()` for some point groups

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#123]
As I tried to plot rotations sampled with `orix.sampling.get_fundamental_region()` to address issue #122, I encountered

```python
>>> from orix import quaterion
>>> pg = quaternion.symmetry.Oh
>>> fr = quaternion.OrientationRegion.from_symmetry(pg)
>>> plot_data = fr.get_plot_data()
/home/hakon/kode/orix/orix/quaternion/orientation_region.py:202: RuntimeWarning: divide by zero encountered in reciprocal
  x = 2 * np.arctan(x ** -1)
```

Looking at the test for this functionality, I see that only `C1` is tested, which works fine.

**Comment by pc494** [comment]
The full function code is:

```python
from orix.vector import Vector3d

theta = np.linspace(0, 2 * np.pi - EPSILON, 361)
rho = np.linspace(0, np.pi - EPSILON, 181)
theta, rho = np.meshgrid(theta, rho)
g = Vector3d.from_polar(rho, theta)
n = Rodrigues.from_rotation(self).norm.data[:, np.newaxis, np.newaxis]
if n.size == 0:
        return Rotation.from_neo_euler(AxAngle.from_axes_angles(g, np.pi))
d = (-self.axis).dot_outer(g.unit).data
x = n * d
x = 2 * np.arctan(x ** -1)
x[x < 0] = np.pi
x = np.min(x, axis=0)
r = Rotation.from_neo_euler(AxAngle.from_axes_angles(g.unit, x))
return r
```

I think it's an edge case, I would be happy to address it, potentially for a patch release?

**Comment by hakonanes** [comment]
Sorry, but what do you mean by edge case? If we try to bypass the warning, it won't have an effect on the outcome? That sounds good, and appropriate for a patch release, yes!

**Comment by pc494** [comment]
Actually, scrap "edge case", it's a bug, it needs fixing, we can put it in a patch release.

**Comment by hakonanes** [comment]
Great to hear. Thanks a lot for looking into it.

**Comment by hakonanes** [comment]
Closing after explanations and #124.
