### ISSUE TITLE
Issues with reducing rotations/orientations with symmetry, possible bug?

### ISSUE THREAD

**Issue by din14970** [pyxem/orix#125]
I'm trying to work out a solution to the issue I described here: https://github.com/pyxem/diffsims/issues/124

My intended strategy is roughly as follows:
1. Create a list of 3D vectors that will represent the zones for which a template is simulated
    * I do this by creating a grid on the surface of a cube (centered on the origin with sidelength 2) in such a way that the angular increments between grid points towards the [111] corner are equal. After comparison to the ASTAR grid, I'm reasonable confident they also do it like this.
2. Convert the list of vectors to orientations via Euler angles or quaternions. We can make all zones parallel to the z-axis with 2 euler angles. For now I've implemented this with Euler angles because I didn't know anything about quaternions, but it seems the calculation will be easier if I directly generate quaternions.
3. Remove the redundant orientations by symmetry.
3. Make a template library from these orientations
4. Perform the template matching with the slight modification that each template is rotated to best fit the experimental patterns. This should automatically give the third Euler angle. I wanted to follow the example from here: https://scikit-image.org/docs/dev/auto_examples/registration/plot_register_rotation.html#sphx-glr-auto-examples-registration-plot-register-rotation-py

I'm hoping this procedure significantly speeds up template matching. 

I was hoping to rely on oryx/pyxem/diffsims for handling the symmetry, simulation of the DP's and for the basics of the "matching" functionality. However I'm having an issue with step 3 - the symmetrizing.

With 50 equal angle grid points from [001]-[111], my orientations look like:
![image](https://user-images.githubusercontent.com/25320842/94242231-ff3ff880-ff15-11ea-8c63-7ab03d074bcd.png)

Or plot in MTEX IPF-Z:
![image](https://user-images.githubusercontent.com/25320842/94242379-3ca48600-ff16-11ea-9ac3-c3a60f00b320.png)

I try to symmetrize my orientation list `grid` in radians as follows:
```python
q = Rotation.from_euler(grid)
point_group = get_point_group(225, proper=True)
fundamental_region = OrientationRegion.from_symmetry(point_group)
return get_list_from_orix(q[q < fundamental_region], rounding=4)
```

I would expect the IPF-Z figure to look the same, however it now looks like this:
<img width="501" alt="image" src="https://user-images.githubusercontent.com/25320842/94244919-d9b4ee00-ff19-11ea-9020-3648ef26e8fd.png">

Am I doing things incorrectly, or is this a bug? I am using orix v0.5.0.

**Comment by hakonanes** [comment]
Hi @din14970! This work looks promising and I hope you (/we) can get it to work.

The lack of rotations in the last IPF reminds me of the IPF in another diffsims issue https://github.com/pyxem/diffsims/issues/103...

Immediately, without looking more into it, it seems to me that the orientation region excludes too many rotations. I haven't used that functionality myself enough to say if that is the case, or if so, why. I will try to have a look. Could you send me the code lines you used to produce the `grid` variable used in your example above?

I hope @pc494 might have some idea.

**Comment by din14970** [comment]
Hi @hakonanes, thanks for the quick feedback. I also saw that issue when I was digging into why my template library had 300k entries. Indeed it looks like some orientations are incorrectly being cropped out. If it helps, after cropping to symmetry, my orientations look like this in Euler space:

<img width="458" alt="image" src="https://user-images.githubusercontent.com/25320842/94252099-c3139480-ff23-11ea-88c8-0cf0e095f916.png">

My grid is being produced with a monstrous function, excuse me for the mess. At the moment I have two grid options: `linear` and `scaled`. `linear` represents an equally spaced grid of points on the cube surface (which in terms of orientations will oversample near 111 and undersample near 001). `scaled` is constructed such that the angle between 001 and 111 is equally divided between the grid points. This is what I used in my comment above. When plotting the grid spacing grows from the center to the corners. I then convert these grid points to euler angles, however I've come to realize it will be much easier to convert them directly to quaternions.

```python
def get_grid(space_group_number, steps=50, grid_type="linear"):
    # generate an array of vectors in a cartesian coordinate system representing the grid on the cube
    if grid_type=="linear":
        i = np.arange(-steps, steps)/steps
        x, y = np.meshgrid(i, i)
        x, y = x.ravel(), y.ravel()
    elif grid_type=="scaled":
        k = np.arange(-steps, steps)
        theta = np.arctan(np.sqrt(2))/steps
        i = np.tan(k*theta)/np.sqrt(2)
        x, y = np.meshgrid(i, i)
        x, y = x.ravel(), y.ravel()
    else:
        raise ValueError(f"grid type {grid_type} not a valid grid type. Valid options: linear, scaled.")
    z = np.ones(x.shape[0])
    # the minus and plusses are so chosen to avoid overlap on the edges of the cube
    # bottom and top
    bottom = np.vstack([-x, -y, -z]).T
    top = np.vstack([x, y, z]).T
    # east and west
    east = np.vstack([z, x, -y]).T
    west = np.vstack([-z, -x, y]).T
    # north and south
    south = np.vstack([x, -z, y]).T
    north = np.vstack([-x, z, -y]).T
    # combine
    all_vecs = np.vstack([bottom, top, east, west, south, north])
    # convert to euler angles
    norm = np.linalg.norm(all_vecs, axis=1)
    z_comp = all_vecs[:,2]
    # second euler angle
    Phi = np.arccos(z_comp/norm)
    # third euler angle
    x_comp = all_vecs[:,0]
    y_comp = all_vecs[:,1]
    norm_proj = np.linalg.norm(all_vecs[:, :2], axis=1)
    sign = np.sign(y_comp)
    # correct for where we have y=0
    sign[y_comp==0] = np.sign(x_comp[y_comp==0])
    phi2 = sign*np.nan_to_num(np.arccos(x_comp/norm_proj))
    # phi1 is just 0
    phi1 = np.zeros(phi2.shape[0])
    grid = np.rad2deg(np.vstack([phi1, Phi, phi2]).T)
    return grid
```

**Comment by din14970** [comment]
whatever comes out of the function I convert to radians of course to pass to `Rotation.from_euler`

**Comment by pc494** [comment]
> I'm trying to work out a solution to the issue I described here: [pyxem/diffsims#124](https://github.com/pyxem/diffsims/issues/124)
> 
> My intended strategy is roughly as follows:
> 
>1. Create a list of 3D vectors that will represent the zones for which a template is simulated

From the IPF-z you show this seems to work, although diffsims has `get_grid_of_beam_directions` which would ideally be the code used for this stage, either as is, or putting your solution in as a replacement.

>2. Convert the list of vectors to orientations via Euler angles or quaternions.

Seems fine

>3. Remove the redundant orientations by symmetry.

So I think here is the problem. If you combine each beam direction with rotations around the beam (eg) take a [111] pattern and rotate it 1 degree 359 times, you produce symmetry equivalent patterns. The fundamental zone will remove these*; but, crucially, it doesn't need to maintain the IPF-z structure to do this. So all the patterns you hoped to have as [111] on the IPF-z are being shuffled elsewhere (they could be [11-1] or whatever), to see exactly where they go I would just plot [111] and [111] post fundamental zoning on an IPF-z. Although see below.

>4. Make a template library from these orientations

I think you should just skip stage 3 and do this directly.

>5. Perform the template matching with the slight modification that each template is rotated to best fit the experimental patterns. This should automatically give the third Euler angle. I wanted to follow the example from here: https://scikit-image.org/docs/dev/auto_examples/registration/plot_register_rotation.html#sphx-glr-auto-examples-registration-plot-register-rotation-py

Yeah, this is probably how I would do it.

Does that help?

*also note that space group 225 has symmetry operation not considered by an IPF-z for "cubic"

**Comment by din14970** [comment]
> From the IPF-z you show this seems to work, although diffsims has get_grid_of_beam_directions which would ideally be the code used for this stage, either as is, or putting your solution in as a replacement.

Where is that function? I tried the other grid functions before but they gave me some odd results, so I decided to start from scratch.

> So I think here is the problem. If you combine each beam direction with rotations around the beam (eg) take a [111] pattern and rotate it 1 degree 359 times, you produce symmetry equivalent patterns. The fundamental zone will remove these*; but, crucially, it doesn't need to maintain the IPF-z structure to do this. So all the patterns you hoped to have as [111] on the IPF-z are being shuffled elsewhere (they could be [11-1] or whatever), to see exactly where they go I would just plot [111] and [111] post fundamental zoning on an IPF-z. Although see below.

Maybe I am misunderstanding your point. My point is I don't intend to combine beam directions with rotations. Each beam direction is described by one unique orientation in such a way that phi1 = 0 (or such that the rotation axis lies in the X-Y plane). If I wouldn't have any symmetry at all then all those orientations should be unique (if I have the correct mental picture). Hence, without any symmetry, my beam directions should cover the entire sphere as a complete IPF-Z shows:

![image](https://user-images.githubusercontent.com/25320842/94263623-98323c00-ff35-11ea-864c-4aab9b365050.png)

I do not intend to cover SO(3) because then indeed you would also have to sample the third euler angle. When I introduce symmetry, MTEX correctly folds these onto the 001-011-111 triangle for plotting, and since my gridding procedure is symmetric with respect to this triangle all the points overlap. However, if I were to make a template library directly from this as you suggest, then I would have a template for beam directions, for example, [100], [010], [001], [-100], [0-10], [00-1], which in the cubic case are all redundant. My template library would be 60000 templates, but I only need about 1/48th of that, which I was hoping to achieve with orix symmetry. If I do so however and plot the full IPF-Z, it looks as follows. You see that where the {111} points are supposed to be, basically the grid has been emptied. 

![image](https://user-images.githubusercontent.com/25320842/94264245-a765b980-ff36-11ea-91b6-d18e975b586d.png)

Something tells me there is still something wrong here, because there is no way to get a 111 type template if there is no 111 near the z-axis.

**Comment by din14970** [comment]
Sorry I was still including the symmetry in MTEX which makes it confusing

Here is the IPF-Z before "cropping" and without symmetry
![image](https://user-images.githubusercontent.com/25320842/94268994-4d68f200-ff3e-11ea-8e28-63aed400e142.png)

Here is the IPF-Z after symmetrizing with orix:

<img width="847" alt="image" src="https://user-images.githubusercontent.com/25320842/94268175-0e866c80-ff3d-11ea-9903-e0234af6ecac.png">

But basically it highlights that in the image from my previous comment should not contain "holes"

**Comment by pc494** [comment]
https://github.com/pyxem/diffsims/blob/c14836832ed7b01ee0facd59ab1e173b4423d25d/diffsims/generators/rotation_list_generators.py#L164

for the gridding function.

I need to go and have a proper look at this, as there are a number of things going on. I would be surprised if our fundamental zone code had a bug in it though, it's had a fair few iterations and tests. If you (@din14970) could leave some of the MTEX code you have used that would be very helpful

**Comment by din14970** [comment]
@pc494  Thanks for the link. I thought indeed I had already tried this. Using `"cubic"` as argument and converting the list of vectors to my euler formalism with:

```python
all_vecs = get_beam_directions_grid("cubic", 1, equal="angle")
norm = np.linalg.norm(all_vecs, axis=1)
z_comp = all_vecs[:,2]
# second euler angle: around x' = angle between z and z''
Phi = np.arccos(z_comp/norm)
# first euler angle: around z = angle between x and x'
x_comp = all_vecs[:,0]
y_comp = all_vecs[:,1]
norm_proj = np.linalg.norm(all_vecs[:, :2], axis=1)
sign = np.sign(y_comp)
# correct for where we have y=0
sign[y_comp==0] = np.sign(x_comp[y_comp==0])
phi1 = sign*np.nan_to_num(np.arccos(x_comp/norm_proj))
# phi2 is just 0, rotation around z''
phi2 = np.zeros(phi1.shape[0])
grid = np.rad2deg(np.vstack([phi2, Phi, phi1]).T)
```

I get this when I plot it with MTEX:

![image](https://user-images.githubusercontent.com/25320842/94275077-d126dc80-ff46-11ea-9ccf-f52604f5726c.png)

So also here something fishy going on near the {111} pole. Without having dived into the code, it looks like the zones are generated using a spherical coordinate grid, which doesn't scale nicely near the {100} pole and you run into issues when you reach {110}. If I contribute nothing else I would suggest replacing this function. Unless there is a specific reason to do it like this.

I guess a temporary solution could be taking care of some of the symmetry already when generating the list of vectors as you do in the `get_beam_directions_grid` function. For my purposes I could fix it relatively quickly for the cube, but I would like to contribute a more sustainable and general solution. 

As for the MTEX code. I export the list of rotations with

```python
np.savetxt("rotlist.txt", grid, delimiter="\t", newline="\r\n")
```

Then I import in two ways. Without adding symmetry to the orientations:

```matlab
fname = 'rotlist.txt';
ori = orientation.load(fname,'columnNames',{'phi1','Phi','phi2'});
```

With symmetry:

```matlab
cs = crystalSymmetry.load('1534888.cif');
fname = 'rotlist.txt';
ori = orientation.load(fname,'columnNames',{'phi1','Phi','phi2'}, cs);
```
CIF file can be found here: http://cod.crystallography.net/cod/1534888.cif

Plotting:

```matlab
plotIPDF(ori, vector3d.Z, 'all')
```

If symmetry is included and I want to see the entire IPF

```matlab
plotIPDF(ori, vector3d.Z, 'all', 'complete')
```

**Comment by din14970** [comment]
for completeness, generating the vectors with `equal='area'` yields
![image](https://user-images.githubusercontent.com/25320842/94278419-1220f000-ff4b-11ea-97a4-2cdd28e91184.png)

**Comment by pc494** [comment]
Intermediate conclusion number 1, `get_grid_of_beam_directions` has problems of some sort, this upgrades https://github.com/pyxem/diffsims/issues/107 to a bug.

Next step, figure out if `orix` is incorrectly cutting orientation out. I'll have a think.

Also, on a related note, this issue makes it very clear that we really really want (crude) pole figure plotting for orix `0.6.0`

**Comment by din14970** [comment]
I think this issue has been resolved in diffsims
