### ISSUE TITLE
How much should the CrystalMap class do?

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#128]
After discussions (off GitHub) yesterday, @pc494, I realise that we might have different expectations as to what the `CrystalMap` class should do.

Let me start by first describing how I want to use `CrystalMap` in an indexing workflow:
1. An empty CrystalMap with proper navigation shape, step size and scan unit is initialized when loading an EBSD data set from file, in the `EBSD.xmap` property.
2. Various maps of pattern quality ("image quality"), similarity to neighbouring patterns (e.g. average dot product/cross correlation), and virtual imaging maps, i.e. no indexing yet, are stored in the `CrystalMap.prop` (CrystalMapProperties) property, so they can be easily stored along with the CrystalMap HDF5 file.
3. Indexing is performed, and a CrystalMap is returned for each candidate phase (allowing us to easily save/reload these intermediate results). The indexing results (orientations and matching scores) are inspected by plotting experimental patterns with either geometrical simulations (bands and zone axes) overlayed on them, alongside the best matching simulated patterns, or a combination of both. The plot navigator is produced from the CrystalMap, e.g. orientation coloring with a quality metric in the alpha channel.
4. Finally, the different CrystalMaps are merged into one CrystalMap containing the end product with quality metric maps and orientations.

I think the only missing functionality in CrystalMap to enable this workflow is to merge results from different CrystalMaps into one CrystalMap (see https://github.com/pyxem/kikuchipy/pull/234).

I understood your view of CrystalMap to be basically from the end result and on, i.e. a CrystalMap is not created before all results from the different indexing runs are inspected and parsed into the "answer". Is this correct? And what do you think of the workflow proposed above?

I think part of the reason for our differing views on the use of CrystalMap is that you already have saving of intermediate results in your `pyxem.signals.TemplateMatchingResults`, while I hoped to depend only on `CrystalMap` in kikuchipy.

Edit: cc @friedkitteh, @onatlandsmyr.

**Comment by pc494** [comment]
I think the best, long term solution, is to move the pyxem workflow over to this usage of `CrystalMap`; this might have to happen stepwise, but I think that's broadly okay.

**Comment by hakonanes** [comment]
I think the discussion has moved past this issue.
