### ISSUE TITLE
RELEASE version 0.5.1

### ISSUE THREAD

**Issue by pc494** [pyxem/orix#134]
I had been considering this for a little while, but given the nature of the fix in #133  now seems a good time to start thinking about it.

I'm hoping to have:
- [x] #133 IO Fix
- [x] #129 CrystalMap improvement
- [x] #132  addressed
- [ ] A few small documentation updates 

In for the patch. Is 3rd November too pushy a deadline for this?

**Comment by hakonanes** [comment]
Nov 3rd sounds great, will get those PRs done today.

**Comment by pc494** [comment]
I have decided to leave #135 out of this release to leave some time for me to get it into the state I want it. Will package today.

**Comment by hakonanes** [comment]
> I have decided to leave #135 out of this release to leave some time for me to get it into the state I want it. Will package today.

Yeah, it looks good, but I think doctests, or instead putting it in a notebook and testing it with nbval, would be nice.
