### ISSUE TITLE
Replace Travis CI with GitHub Actions

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#142]
See https://github.com/pyxem/pyxem/issues/661.

This replacement is done in kikuchipy (https://github.com/pyxem/kikuchipy/actions/runs/390267628/workflow), will do this for orix within the next week.

**Comment by pc494** [comment]
If you're sure; I'm happy to do one (of diffsims or orix) to spread the workload (given I will need to learn how to make it work for the pyxem release)

**Comment by hakonanes** [comment]
Great, you can do diffsims if that's OK.

Please tell me if you get `coverage` to make a report available for the reporting-action to upload to Coveralls! And installing dependencies with conda (which would be nice).

**Comment by hakonanes** [comment]
Done in #143
