### ISSUE TITLE
Improving the orix demos and documentation

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#149]
I would like for orix to adopt the demos-and-documentation-setup we now have in kikuchipy from v0.3.0:
* Jupyter notebook demos as [part of the package documentation](https://github.com/pyxem/kikuchipy/tree/master/doc)
* Uses [nbsphinx](https://nbsphinx.readthedocs.io/en/0.8.1/) (called indirectly by Sphinx when the docs are built via `make html`) to convert the notebooks to reStructuredText files included in the [Sphinx documentation](https://kikuchipy.org/en/stable/)
* Users can run the notebooks interactively [via Binder in their browsers](https://mybinder.org/v2/gh/pyxem/kikuchipy/v0.3.1?filepath=doc)
* Documentation can be written solely in notebooks
* Whether the notebooks run or fail is determined by Read the Docs on every PR check
* No need for a separate demo repository

Necessary changes for orix to adopt this setup:
- [x] Some test data as part of a `orix.data` module for the notebooks to use. A few small datasets (less than 0.5 MB, e.g.) should be part of the package. Larger data can be downloaded from an external source (similar to [kikuchipy-data](https://github.com/pyxem/kikuchipy-data), with the help of the `pooch` package (used by e.g. `scikit-image`), into a cache on the user's machine *once*, and then loaded directly from the `orix.data` via a safe registry. This introduces a pooch dependency.
- [x] nbsphinx dependency (#152)
- [x] Some notebooks in the orix/doc directory (like the crystal map notebook) (#152)

If there is interest, I can set this up.

**Comment by pc494** [comment]
This seems like a good idea. No pressure/rush

**Comment by hakonanes** [comment]
Since I've done it once already it shouldn't be too difficult to add the module with a crystal map and port the notebook over here. The challenge is, if we want to archive the orix-demos, to make the other more heavy-duty notebooks over.

**Comment by hakonanes** [comment]
I've bumped a `orix.data` module to v0.7.

**Comment by hakonanes** [comment]
A data module was added in #318, and will be released as part of 0.9.
