### ISSUE TITLE
Format of the coordinates and axes of stereographic projections of northern and southern hemispheres

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#153]
I'm combining the `StereographicProjection` implemented by @din14970 with the `StereographicPlot` from @bm424 and @dnjohnstone in #62, which is improving every time I understand something new about the transformation framework in Matplotlib, which is rather complex (at least for me).

However, I have a couple of questions concerning the best way to display polar coordinates and the axes in a combined plot with both the upper and lower hemispheres:

This code

```python
import matpotlib.pyplot as plt
from orix import plot, projections, vector
v = vector.Vector3d([
    [0, 0, 1],
    [1, 0, 1],
    [1, 1, 1],
    [0, 0, -1],
    [-1, 0, -1],
    [-1, -1, -1],
])

fig, ax = plt.subplots(ncols=2, subplot_kw=dict(projection="stereographic"))

ax[0].pole = -1
ax[0].scatter(v)  # Lower hemisphere points aren't plotted
ax[0].show_hemisphere()
ax[0].set_xlabel()
ax[0].set_ylabel()
for vi in v[:3]:
    ax[0].text(vi, s=vi._nice_string_repr())

ax[1].pole = 1
ax[1].scatter(v)  # Upper hemisphere points aren't plotted
ax[1].show_hemisphere()
ax[1].set_xlabel()
ax[1].set_ylabel()
for vi in v[3:]:
    ax[1].text(vi, s=vi._nice_string_repr())
```

produced this figure

![stereographic1](https://user-images.githubusercontent.com/12139781/107783525-a77e1e80-6d4a-11eb-9c4c-1651b3bbe2b1.png)

In the upper projection, the azimuthal coordinate goes counterclockwise from 0 to 2 pi, and the polar coordinate goes radially from 0 to pi/2. In the lower projection, the azimuthal coordinate still goes counterclockwise from 0 to 2 pi, but the polar coordinate goes inverse radially from pi / 2 to pi (think of the zenith angle going from northern to southern pole)...

The coordinates in the Matplotlib interactive plotting data bar when hovering over [111] in the upper projection:

![Skjermbilde fra 2021-02-12 15-59-20](https://user-images.githubusercontent.com/12139781/107784641-fbd5ce00-6d4b-11eb-9f12-732ceb74bf1e.png)

and [-1-1-1] in the lower projection:

![Skjermbilde fra 2021-02-12 16-02-58](https://user-images.githubusercontent.com/12139781/107784654-fd9f9180-6d4b-11eb-9e02-10eb875a064b.png)

I plan to make the polar angles to be the same in both projections, what do you think? And should the azimuthal coordinate in the lower projection go clockwise?

Also, should we plot the "Y" label in the lower projection at the bottom (rotating about X), or should we plot "-Y" inplace of the "Y"?  And what about "Z" and "-Z"? Once we settle on a default, I think I can make it so that the user can do whatever they like.

**Comment by pc494** [comment]
> I plan to make the polar angles to be the same in both projections, what do you think? And should the azimuthal coordinate in the lower projection go clockwise?

I think this is a bad idea. I think that the polar angle represents a physical angle, from the "north pole" to the point you are currently hovering over in projection and so should be kept. Similarly, the azimuthal one as far as I can tell.

> Also, should we plot the "Y" label in the lower projection at the bottom (rotating about X), or should we plot "-Y" inplace of the "Y"? And what about "Z" and "-Z"? Once we settle on a default, I think I can make it so that the user can do whatever they like.

Do you think the "Y" label in the current plot is in an inconsistent place. It's how I would naturally have gone to plot such a diagram

**Comment by hakonanes** [comment]
> Do you think the "Y" label in the current plot is in an inconsistent place. It's how I would naturally have gone to plot such a diagram

so i think the lower projection is to a plane below the unit sphere, that that is the best way to visualize it. then the polar angle makes sense, the axis can stay in the same position, and the azimuthal can go the same way.

**Comment by pc494** [comment]
Okay, so I would have used the equatorial plane for both. We should agree a convention for this (as, I now see, you were trying to do @hakonanes!)

**Comment by hakonanes** [comment]
i just have to wrap my head around how to view the lower hemisphere projection onto the equatorial plane... how it is now might be best, is what youre saying?

**Comment by pc494** [comment]
I think my natural choice of convention would be:

In the upper hemisphere draw a line from the point to the South pole, take the intersection with the equatorial plane.
In the lower hemisphere you draw your line from the point to the North pole, take the intersection etc.

(For points on the equator you get the same result either way, going via North or South pole)

**Comment by hakonanes** [comment]
definitely, that is how niels implented it, and how it is used. im talking about whether the coordinates used in the data bar (azimuth, polar/zenith) and axes labels should be the same for both upper and lower.

**Comment by din14970** [comment]
This looks cool @hakonanes ! I really like the grid. May be best to try to stay as consistent as possible with MTEX. Not sure how these plots would look there. Keeping axes the same means that you are viewing the projection plane from the same direction, regardless of projection pole. In this case you view the plane from positive z down. In my opinion this makes most sense. If you would view the projection from the bottom for the southern hemisphere, the image should be mirrored across x. As @pc494 mentions, I indeed assumed in my implementation that the projection plane is the equitoral plane.

**Comment by hakonanes** [comment]
Glad to hear you like it, @din14970! Then I can move on with the implementation as it is above.

I would just like to restate that for the lower projection the polar (zenith?) angle goes from 90 to 180 degrees when going inward, while for the upper projection this angle goes from 0 to 90 degrees when going outward.

**Comment by din14970** [comment]
> I would just like to restate that for the lower projection the polar (zenith?) angle goes from 90 to 180 degrees when going inward, while for the upper projection this angle goes from 0 to 90 degrees when going outward.

Yes I think that's normal because of the way the polar coordinates are defined in orix. If you would define the polar coordinates relative to the equatorial plane then the elevation angle would go from -90 to 0 for the southern hemisphere and from 0 to 90 for the northern hemisphere.

**Comment by hakonanes** [comment]
I agree. By the way @din14970, I wrote the `Vector3d.to_polar()` based on the [ISO standard](https://mathworld.wolfram.com/SphericalCoordinates.html) on a request from @pc494: if you have any recommandations for how to improve that part of the code, I would be happy to hear it.

**Comment by din14970** [comment]
> based on the ISO standard on a request from @pc494

I would agree with this and think it is logical to keep it this way. In the end those points just represent coordinates, so even though it's maybe a bit weird that the southern and northern hemisphere are "inverted", users would care most about seeing the actual coordinates when they hover their mouse over the points.

**Comment by pc494** [comment]
@hakonanes; just looking at the hovering images in the original post. They are using phi (which looks correct) and then rho, I suppose this is because it's the **radial** coordinate on the 2D surface, which corresponds to the polar coordinate on the surface of the sphere?

**Comment by hakonanes** [comment]
Yes, rho is the polar/zenith angle on the surface of the sphere, and it's radial coordinate is then given by tan(zenith / 2). I think we should use theta (as it is now) and phi (instead of rho). What do you think?

These coordinate variables should correspond with the spherical coordinates for Vector3d (r, theta, phi). I suggest we rename these coordinates `Vector3d.radial`, `.zenith`, `.azimuth`, or `.radial`, `.polar`, `.azimuth`, to reduce possible confusion. This way the user doesn't have to check the link in the docstring (https://mathworld.wolfram.com/SphericalCoordinates.html) to know how theta and phi are defined.

**Comment by pc494** [comment]
> Yes, rho is the polar/zenith angle on the surface of the sphere, and it's radial coordinate is then given by tan(zenith / 2). I think > > we should use theta phi (as it is now) and phi theta (instead of rho). What do you think?

I agree

> I suggest we rename these coordinates

I agree again, I would have `.radial, .polar, .azimuth` as my pick.
