### ISSUE TITLE
Add plot methods to Vector3d

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#162]
Turns out we can avoid circular imports simply by doing the following

```python
class Vector3d:
[...]
    figure = None  # Property for easy figure access
[...]
    def plot(self):
        import orix.plot

        fig, ax = plt.subplots(subplot_kw=dict(projection="stereographic"))
        ax.scatter(self)
        self.figure = fig
```

Then can we do this

```python
from orix import vector
v = vector.Vector3d([[0, 0, 1], [1, 0, 1], [1, 1, 1]])
v.scatter()
v.figure.savefig("/home/hakon/vectors.png", bbox_inches="tight")
```

which produces this

![vectors](https://user-images.githubusercontent.com/12139781/109665325-53f33980-7b6e-11eb-8d19-8823026f8f95.png)

This means that we have to import the `orix.plot` module on *every* call to `.plot()`, but I think that should be OK. What do you think, @pc494 and @din14970?

If we go for this solution, the other issues we have to solve, that I can think of, are
* ~making the Matplotlib figure and axes objects easily available (in private `_figure` and `_axes` attributes?)~ already answered this above, with `Vector3d.figure`.
* allowing customization ~and adding to~ (I didn't get this to work with add_subplot or add_axes) the current figure/axes
* ~easy creation of new figures, also putting multiple side by side~ Except for having a hemisphere="both" keyword argument to `scatter()`, this quickly becomes very custom and opiniontated, so I won't spend any time on it.
* decide on which plotting methods we should make available from `Vector3d`, and what they should be called

If we go forward with this, we should make sure to make nothing available only via the class plotting methods, i.e. also make it available and customizable from the Matplotlib projections. The class plotting methods should only call the projection methods.

**Comment by din14970** [comment]
I've never found a proper solution how to deal with all the matplotlib objects. Do you return/store the fig? The ax? The objects on the ax? I'm not a huge fan of having a "figure" property in the vectors, it seems somehow not really a property. Why not just return figure, axis or both with the plot function?

>  import the orix.plot module on every call to .plot()
I think imports are cached, so once you've done it, calling it again should cause no significant overhead. I experimented with this in a personal project where I imported the hyperspy api on some function calls. The first time is super slow, the second time it's nothing.

> allowing customization 
Can't we pass in *args and **kwargs which go directly into scatter? Perhaps it is possible to define a couple extra flags, for example for creating the grid on the plot etc. Or if you return the figure or axis objects from the method, then a user can still paste on additional configuration post-factum

Just my two cents.

**Comment by hakonanes** [comment]
Thanks for the quick feedback, @din14970!

The axes (one or a list) are included as attributes to Matplotlib's `Figure`, so these can be accessed as `Vector3d.figure.axes`.

HyperSpy stores the current figures in `BaseSignal._plot`. I often access the navigation or signal figures plots via `._plot.signal_plot` or `._plot.navigation_plot`. This way I can continue to customize the figures, and also save them via savefig. I strongly recommend we add the `figure` attribute, and that we clearly state that the current figure is available from there. If we call `scatter()` again, the attribute is overwritten.

Of course, you're right in that imports are cached. So that's no worry then.

By customization I mean e.g. creating a grid of figures, say 2-by-2, with various stereographic projections within them. What I've opted for now is just to support almost all functionality currently in the stereographic notebook via a one-line command. We can add more stuff later if we want. I think the most important thing is to support simple and often used use cases via `scatter()` with parameters, while more "advanced" customization should be done either via `Vector3d.figure` or by doing it the "old" way.

**Comment by hakonanes** [comment]
Thinking a bit more about the `Vector3d.figure`, I agree that it's not really a property of the vector, but it is *really* convenient to have this easy access to the current figure.

**Comment by din14970** [comment]
> HyperSpy stores the current figures in BaseSignal._plot

I guess if hyperspy is doing it this way it should be fine. Maybe to stay consistent as possible we can also just call it _plot?

> By customization I mean e.g. creating a grid of figures, say 2-by-2, with various stereographic projections within them. What I've opted for now is just to support almost all functionality currently in the stereographic notebook via a one-line command. We can add more stuff later if we want. I think the most important thing is to support simple and often used use cases via scatter() with parameters, while more "advanced" customization should be done either via Vector3d.figure or by doing it the "old" way.

Aha, yes of course. I was thinking of the plot method more as a quick and dirty visualisation technique, as one also has in hyperspy. But usually when I create figures for papers I anyway default back to the matplotlib api because of flexibility. So I would expect users do the same.

**Comment by hakonanes** [comment]
I've made all functionality in the stereographic projection notebook (except for symmetry element plotting) available from the `Vector3d.scatter()` method, demonstrated in these docs built from #158: https://orix--158.org.readthedocs.build/en/158/stereographic_projection2.html

**Comment by din14970** [comment]
Looks really awesome @hakonanes ! I've said it before but those jupyter notebook based docs are also a really nice touch.

**Comment by hakonanes** [comment]
Glad to hear it, @din14970! Totally agree, mostly thanks to [nbsphinx](https://github.com/spatialaudio/nbsphinx). That package greatly simplifies creating, updating and maintaining documentation.

**Comment by hakonanes** [comment]
I consider this work well on its way in #158, and will close this once that PR is merged.
