### ISSUE TITLE
from_euler() could warn if it looks like the input is in degrees 

### ISSUE THREAD

**Issue by pc494** [pyxem/orix#168]
from_euler() could warn if it looks like the input is in degrees, eg:

```python
>>> z = [40,10,5]
>>> q = quaternion.from_euler(z)
```
`
Warning : The method "from_euler" takes angles in radians, it appears you might instead be using degrees
`

I think MTEX does this, for context such a routine would have caught https://github.com/pyxem/pyxem/issues/752 a lot quicker.

@hakonanes thoughts?

**Comment by hakonanes** [comment]
Totally agree!
