### ISSUE TITLE
Misorientation.set_symmetry() for octahedral symmetry 

### ISSUE THREAD

**Issue by EirikOpheim** [pyxem/orix#17]
I believe there is a small bug in `Misorientation.set_symmetry()` for octahedral symmetries. The bug is that for Euler angles (-45,0,0) and (45,0,0) the distance is reported to be 90 degrees, while it should be 0 degrees. For (0,0,0) and (90,0,0) it works fine. Even for (-45.0001,0,0) and (44.9999,0,0), so it is just for a special case that this goes wrong. 

There is also another issue that I am not quite sure about for this method. The Euler angles (10,10,0) and (-80,10,0) have a non-zero distance. I would expect them to have zero distance but their distance is the same as for (0,0,0) and (10,10,0). I am not sure if this is correct, as at least the diffraction patterns, as simulated in `DiffractionLibraryGenerator.get_diffraction_library()` are equal for the two for an FCC structure. 

To reproduce, simply run:
```
ori = Orientation.from_euler([np.radians(np.asarray([45,0,0]))]).set_symmetry(O)
ori2 = Orientation.from_euler(np.radians(np.asarray([-45,0,0]))).set_symmetry(O)
misori_base = Misorientation(~ori * ori2)
misori = misori_base.set_symmetry(O, O)
np.rad2deg(misori_base.angle.data)
```

I am not quite sure how to resolve the issue, but I am guessing that both (45,0,0) and (-45,0,0) are defined as inside the symmetry region of the O symmetry.

**Comment by pc494** [comment]
I have now split this issue into #18 and #19 as it contains two distinct concerns.

**Comment by pc494** [comment]
@EirikOpheim could you add the `imports` to the code snippet?

**Comment by EirikOpheim** [comment]
Sure, added imports to #19
