### ISSUE TITLE
Handling of edges of fundamental zone

### ISSUE THREAD

**Issue by pc494** [pyxem/orix#18]
Pulled out of #17 

**Quote: EirikOpheim**

I believe there is a small bug in Misorientation.set_symmetry() for octahedral symmetries. The bug is that for Euler angles (-45,0,0) and (45,0,0) the distance is reported to be 90 degrees, while it should be 0 degrees. For (0,0,0) and (90,0,0) it works fine. Even for (-45.0001,0,0) and (44.9999,0,0), so it is just for a special case that this goes wrong.

To reproduce, simply run:
```
ori = Orientation.from_euler([np.radians(np.asarray([45,0,0]))]).set_symmetry(O)
ori2 = Orientation.from_euler(np.radians(np.asarray([-45,0,0]))).set_symmetry(O)
misori_base = Misorientation(~ori * ori2)
misori = misori_base.set_symmetry(O, O)
np.rad2deg(misori_base.angle.data)
```
I am not quite sure how to resolve the issue, but I am guessing that both (45,0,0) and (-45,0,0) are defined as inside the symmetry region of the O symmetry.

**End quote**

This belies a general issue. Often (sometimes with some explanation) the literature will leave degenerate rotations in. For example when working with euler angles, inclusive 0,m * pi ranges are used. In theory, either 0 or m * pi would suffice, but in practice people tend not to worry about it. Similarly, axis angles tend include pi in the range, which leaves both [1,0,0] pi and [-1,0,0] pi, a degenerate pair in.

In orix workflows this problem should stop being a problem once we run the clustering step.

**Comment by EirikOpheim** [comment]
I see, thank you for a good explanation!

**Comment by dnjohnstone** [comment]
@pc494 what's the status of this thing?

**Comment by EirikOpheim** [comment]
> @pc494 what's the status of this thing?

I have found a way to get the correct distance with a function already in Orix. By using 

```
ori = [45,0,0]
ori2 = [-45,0,0]
orientations = list([ori, ori2])
ori = Orientation.from_euler(np.deg2rad(orientations))
misori_base = Misorientation(ori).set_symmetry(symmetry,symmetry)
np.rad2deg(misori_base.distance())
```
We get a 2 by 2 matrix where the [0,1] and [1,0] elements are the distance from ori to ori2 in radians. This code gives 0 degrees distance for the example above, and I have not found any issues with this solution yet (I haven't studied the code in dept, but it seems to be working).

**Comment by pc494** [comment]
Unclear, it might have been fixed by #60. In general I think we are still leaving two equivalent rotations in.

It's worth pointing out that the `.distance() `method is designed to account for the symmetry & so the fact that it is giving the correct answer is encouraging.

**Comment by dnjohnstone** [comment]
Ok, I'm going to mark this as a 0.3.0 task for now then...

**Comment by dnjohnstone** [comment]
I think this is probably not an issue any more? Do others agree and can we close for a 0.3.0 release?

**Comment by pc494** [comment]
It's a documentation issue really, seems easiest to close it for now.
