### ISSUE TITLE
Test examples in docstrings with doctest via pytest

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#187]
After @magnunor set up testing of docstring examples in pyxem with [doctest](https://docs.python.org/3/library/doctest.html) via [pytest](https://docs.pytest.org/en/stable/doctest.html), I did that for kikuchipy as well. All docstring examples are now tested via the [GitHub Actions running on ubuntu-latest](https://github.com/pyxem/kikuchipy/blob/master/.github/workflows/build.yml#L37) in kikuchipy (I experienced some issues running the tests on Windows, and deemed ubuntu Python 3.8 and 3.9 sufficient). Some additions to the [pytest configuration](https://github.com/pyxem/kikuchipy/blob/master/kikuchipy/conftest.py#L394) were necessary, as well as fixing errors discovered in the docstring examples.

I would like to set this up for orix. What do people think?

**Comment by pc494** [comment]
I think this is a good addition, I imagine it'll be a little easier for `orix` as we don't need a bunch of data modules?

**Comment by hakonanes** [comment]
Actually, come to think of it, it will be challenging to test at least the CrystalMap docstring examples without a `orix.data` module to load example data from (as explained here https://github.com/pyxem/orix/issues/149)... It is easy in kikuchipy because we have our `kikuchipy.data` module (see e.g. [this docstring example](https://github.com/pyxem/kikuchipy/blob/master/kikuchipy/signals/ebsd.py#L880)).

Note that all orix example data can reside in an orix-data repository here on GitHub, so we don't have to include them in the package on PyPI, but can still be downloaded via `xmap = orix.data.super_duplex_stainless_steel(allow_download=True)`.

Considering that you're in favor of docstring testing @pc494, I will set up testing of all docstring examples except the ones where a crystal map or similar files are needed, which will be ignored.

**Comment by pc494** [comment]
> Considering that you're in favor of docstring testing @pc494, I will set up testing of all docstring examples except the ones where a crystal map or similar files are needed, which will be ignored.

This seems like a good plan to me.

> Note that all orix example data can reside in an orix-data repository here on GitHub, so we don't have to include them in the package on PyPI, but can still be downloaded into a local cache via `xmap = orix.data.super_duplex_stainless_steel(allow_download=True)`.

We can then tackle this problem at the `0.7`, my instinct (keep packages small on pypi) is being offset by the fact kikuchipy only runs to 5MB. But again, that's for `0.7` chat

**Comment by hakonanes** [comment]
Great!

> We can then tackle this problem at the `0.7`, my instinct (keep packages small on pypi) is being offset by the fact kikuchipy only runs to 5MB. But again, that's for `0.7` chat

I agree, an `orix.data` module is for v0.7.

For your information, we have three bigger files, about 1 MB each, in kikuchipy: a nice .gif for the docs, an EBSD master pattern of Nickel, part of `kikuchipy.data`, and an HDF5 file in EDAX TSL's format for testing that reader. I will remove the .gif in the future, reduce the HDF5 file size, and probably move the master pattern to the kikuchipy-data repo.

**Comment by pc494** [comment]
Honestly, I get emails far bigger than 1MB pretty regularly so I wouldn't worry to much about it if it improves user experience.

**Comment by hakonanes** [comment]
When we do this, we can add a few example docstrings as well, including the one mentioned in https://github.com/pyxem/orix/pull/202#issuecomment-860565878.
