### ISSUE TITLE
Computing misorientations

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#191]
We should add `orix.quaternion.Orientation.angle_with()` to consider symmetry, i.e. overwrite `Rotation.angle_with()`. This could be done by generating all symmetrically equivalent orientations, computing the angles, and taking the minimum angle. We could add a public method `Orientation.symmetrise()` to get the symmetrically equivalent orientations as a new instance.

I haven't looked at the `_distance()` function to calculate misorientations, but I guess this approach would be an alternative?

**Comment by pc494** [comment]
This could be very slow for high symmetry systems - but the code is all there in the `_distance()` function as far as I know. I think orientation already has a method to generate the symmetrically equivalent rotations but I might be misremembering.

**Comment by hakonanes** [comment]
You're right, from `Misorientation.equivalent()`, I could have a look at this.

**Comment by hakonanes** [comment]
I've added `Orientation.angle_with()` and `Orientation.distance_to()` in https://github.com/pyxem/orix/pull/196.
