### ISSUE TITLE
Going from almost equal rotations to orientations introduces a misorientation

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#192]
It seems like `Orientation.set_symmetry()` with point group m-3m introduces a misorientation of about 90 degrees to two rotations which are almost identical:

```python
>>> import numpy as np
>>> from orix.quaternion import Orientation, Rotation
>>> from orix.quaternion.symmetry import Oh
>>> from orix.vector import AxAngle
>>> r = Rotation.from_euler(np.deg2rad([[-89.9, 45, 134.9], [-90.0, 44.9, 45]]))
>>> print(np.rad2deg(r[0].angle_with(r[1]).data))
[89.97083784]
>>> o = Orientation(r).set_symmetry(Oh)
>>> print(np.rad2deg(o[0].angle_with(o[1]).data))
[119.88459286]

# Rotate to almost perfect alignment

>>> r[1] = Rotation.from_neo_euler(AxAngle.from_axes_angles([0, 0, 1], -np.pi / 2)) * r[1]
>>> print(np.rad2deg(r[0].angle_with(r[1]).data))
[0.12587899]

# Misorientation of about 90 degrees reintroduced?

>>> o2 = Orientation(r).set_symmetry(Oh)
>>> print(np.rad2deg(o2[0].angle_with(o2[1]).data))
[89.90008731]
```
I would expect that the last misorientation angle would be approximately 0. Am I wrong? With MTEX' `orientation.angle()` method I get a misorientation angle of about 0.

**Comment by hakonanes** [comment]
OK, so I see that the correct way to get a misorientation angle between two orientations is via `Misorientation.distance()`. Continuing on the code snippet above:

```python
>>> m01 = (o2[0] - o2[1]).set_symmetry(Oh, Oh)
>>> m01.distance()
array([[0.]])
```

I still would like to leave this open until we have written over `Orientation.angle_with()` to use `Misorientation.distance()`, because that is the behaviour I would expect from `Orientation.angle_with()`.

**Comment by pc494** [comment]
My feeling is that `angle_with` is ambiguous and should probably be removed. The `.distance()` method seems like a much better work horse.

**Comment by hakonanes** [comment]
Yeah, that is a viable option as well, I'm open to that solution.

**Comment by hakonanes** [comment]
With the changes in #196, I get

```python
>>> r = Rotation.from_euler(np.deg2rad([[-89.9, 45, 134.9], [-90.0, 44.9, 45]]))
>>> print(np.rad2deg(r[0].angle_with(r[1]).data))
[89.97083784]
>>> o = Orientation(r).set_symmetry(Oh)
>>> print(np.rad2deg(o[0].angle_with(o[1]).data))
[62.67543291]
>>> r[1] = Rotation.from_neo_euler(AxAngle.from_axes_angles([0, 0, 1], -np.pi / 2)) * r[1]
>>> print(np.rad2deg(r[0].angle_with(r[1]).data))
[0.12587899]
>>> o2 = Orientation(r).set_symmetry(Oh)
>>> print(np.rad2deg(o2[0].angle_with(o2[1]).data))
[0.12587899]
```

which is more like what I would expect.
