### ISSUE TITLE
Grids/rotation lists

### ISSUE THREAD

**Issue by shogas** [pyxem/orix#2]
This is a continuation from https://github.com/pyxem/pyxem/issues/304.

As I understand it, we would rather implement rotation lists in texpy than in pyxem directly. Should this live under `texpy/grid`?

I have a "pyxem" implementation at https://github.com/shogas/pyxem/blob/rotation_list/pyxem/utils/sim_utils.py. I think the base structure is fine, but I will rewrite it to fit the texpy style if it should be part of texpy.

Do we want to add a dependency to https://github.com/diffpy/diffpy.structure? My current implementation actually only needs the transformation matrix from the lattice (`diffpy.structure.lattice.Lattice.stdbase`), and it might be good to keep texpy independent on a specific structure representation.

**Comment by bm424** [comment]
Hey @shogas, thanks for this! I haven't looked at `/grid` in quite a while so the code in it is a bit out of date compared to the rest of it but I think this looks pretty ideal for it.

As texpy (hopefully) evolves I think incorporating some elements of diffpy will probably save a lot of labour, but while it's still in its current stage as you say I think keeping the `diffpy.structure` dependency out of it would be better. 

texpy still needs a lot of work and one of the things that needs implementing is proper handling of miller indices (currently everything is just cartesian), so in the short term you could probably simply forget the lattice dependency.

(I'll need to sit down with your code at some point and see exactly what it does, it may be that using texpy's `Symmetry` objects could also be the way forward).

As for implementation of this code, you're generating a grid on SO(3), so we'll need a new submodule (probably `so3grid`) and class (SO3Grid). Then, I think your ported function would exist as a `from_stereographic_vertices` (or similar) class method, just acknowledging that other generating methods might exist in future. For texpy style, the output will be a `Rotation` object (internally a bunch of normalised quaternions).

This is up to you, but I'd also consider converting the matrix math in your function to the quaternion math used throughout texpy (for example, an axis-angle rotation can be generated via `Rotation.from_axis_angle(AxAngle.from_axes_angles(axis, angle))`). 

Thanks again for developing the method, it looks like it'll be very valuable!

**Comment by dnjohnstone** [comment]
@pc494 do you think this is still relevant? Or superseded by events?

**Comment by pc494** [comment]
We will probably do this, but it can be a new issue as quiet a lot has happened since this discussion.
