### ISSUE TITLE
On the use of black for code style

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#208]
I've experienced some inconsistencies with the use of black in kikuchipy. The black configuration apparently differed between contributors, most likely because I had installed black via pre-commit while others perhaps had not. To make the use of black consistent, we did two things in kikuchipy:
* Use default black, by removing the black configuration (in pyproject.toml). This ment mostly going from 80 (custom) to 88 line lengths.
* Let black check code contribution in PRs via a GitHub Action. This action took typically ~15 s for kikuchipy PRs.

I suggest we do this as well for orix. I can set up a PR if there is interest.

**Comment by hakonanes** [comment]
Also, we added a [PR check](https://github.com/pyxem/kikuchipy/blob/59f5f3825511d335a0d5c49518ac644e3190065a/.github/workflows/build.yml#L15) of the MANIFEST.in file used via the [manifix package](https://github.com/vidartf/manifix). From their README:
> This is meant as a helper to check that no files meant for inclusion in the package are left out, simply because you forgot to update the manifest.

If there is interest in this, I can add this as well. This will add a dev dependency on manifix in setup.py.

**Comment by hakonanes** [comment]
If we were to set up a black code style PR check, we must first run black through it all. I suggest you do this @pc494, unless you want me to do it.

**Comment by pc494** [comment]
> Also, we added a [PR check](https://github.com/pyxem/kikuchipy/blob/59f5f3825511d335a0d5c49518ac644e3190065a/.github/workflows/build.yml#L15) of the MANIFEST.in file used via the [manifix package](https://github.com/vidartf/manifix). From their README:
> 
> > This is meant as a helper to check that no files meant for inclusion in the package are left out, simply because you forgot to update the manifest.
> 
> If there is interest in this, I can add this as well. This will add a dev dependency on manifix in setup.py.

Could you explain what this does/how it works? I feel like I've only ever seen the license file in our MANIFEST.ini?

**Comment by pc494** [comment]
> If we were to set up a black code style PR check, we must first run black through it all. I suggest you do this @pc494, unless you want me to do it.

Yes, I will do this

**Comment by hakonanes** [comment]
> Could you explain what this does/how it works? I feel like I've only ever seen the license file in our MANIFEST.ini?

We've decided to include the documentation with kikuchipy on pip (can be viewed in the [.tar.gz file on PyPI](https://pypi.org/project/kikuchipy/#files)), and we told Python to include it via our [MANIFEST.in](https://github.com/pyxem/kikuchipy/blob/master/MANIFEST.in). 

orix does not ship the documentation with the code ([on PyPI](https://pypi.org/project/orix/#files)). Since the LICENSE file is listed in our setup.py, I actually think we can remove the MANIFEST.in file.

A nice [StackOverflow answer](https://stackoverflow.com/a/24727824).

**Comment by hakonanes** [comment]
Searching a bit more, I find [this comment](https://github.com/pypa/setuptools_scm/issues/190#issuecomment-492339946) compelling, and I agree with the commenter's view that documentation and tests should be distributed along with the Python functionality.

**Comment by hakonanes** [comment]
OK, I suggest:
* Run black on all files with default configuration
* Create black CI check
* Add documentation to distribution on PyPI by listing necessary files in MANIFEST.in
* Create manifest CI check using manifix
