### ISSUE TITLE
Misorientation.equivalent() has a broken codepath

### ISSUE THREAD

**Issue by pc494** [pyxem/orix#21]
The property `equivalent` (of `Misorientation`, but inhereted by `Orientation`) is broken for the non-grain exchange case. Inspecting the copy+paste snippet below it's clear that for `Gl._tuples != Gr._tuples` we will always get an UnboundLocal error (on "`orientations`")

```
    def equivalent(self):
        """Equivalent misorientations
        Returns
        -------
        Misorientation
        """
        Gl, Gr = self._symmetry
        if Gl._tuples == Gr._tuples:  # Grain exchange case
            orientations = Orientation.stack([self, ~self]).flatten()
        equivalent = Gr.outer(orientations.outer(Gl))
        return self.__class__(equivalent).flatten()
```

**Comment by dnjohnstone** [comment]
@pc494 do you know how to fix this? It would be good to have tied up for 0.2.0 release....

**Comment by pc494** [comment]
Short answer, no not properly. Correct answer, yes I could find out.
