### ISSUE TITLE
Streamline the from_euler method to better work with MTEX

### ISSUE THREAD

**Issue by pc494** [pyxem/orix#215]
As discussed https://github.com/pyxem/orix/pull/201#issuecomment-880784662 in I've recently discovered how MTEX's convention differs from Bunge's. Currently we use the (undocumented) convention keyword '`Krakow_Hielschler`' to deal with this. But testing suggests we could simply reroute that through direction kwarg.

This would simplify the API somewhat and is also a lot easier to document.

**Comment by hakonanes** [comment]
great. would this be a patch or minor release change?

**Comment by pc494** [comment]
it's patch level (non-breaking and mainly documentation), but I think realistically it won't happen until I've got a fair bit of time to code (October or so) at which point I'll try and push all of the minor release elements through as well. I've slightly gone off patching except for urgent cases.
