### ISSUE TITLE
Add symmetry argument to Orientation-based classes __init__

### ISSUE THREAD

**Issue by harripj** [pyxem/orix#241]
As mentioned by @hakonanes in https://github.com/pyxem/orix/pull/240#discussion_r746712531, it would be useful to have a symmetry argument in the `__init__` methods of `Orientation` and `Misorientation` along the lines of `Misorientation.__init__(self, data, symmetry=None)`.

To be considered in conjunction with/after #240.

**Comment by pc494** [comment]
+1 for this.
