### ISSUE TITLE
Rotation.to_euler() shouldn't return negative Euler angles

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#244]
`Rotation.to_euler()` should return Euler angles in the ranges [0, 2pi], [0, pi], [0, 2pi] according to the first author of the 2015 paper ["Consistent representations of and conversions between 3D rotations"](http://dx.doi.org/10.1088/0965-0393/23/8/083501), Dave Rowenhorst, if we follow the definitions of that paper, which we say we do [in the code](https://github.com/pyxem/orix/blob/master/orix/quaternion/rotation.py#L378). However, I get negative Euler angles:

```python
>>> import numpy as np
>>> from orix.quaternion import Rotation
>>> rot = Rotation.from_euler(np.radians((45, 10, 45)))
>>> np.degrees(rot.to_euler())
array([[-45.,  10.,  45.]])
```

After a quick check, it doesn't seem like MTEX ever returns negative Euler angles, either.

I think we should always return positive Euler angles.

**Comment by hakonanes** [comment]
See https://github.com/drowenhorst-nrl/PyEBSDIndex/issues/1#issuecomment-953319318 for Dave's comment.

**Comment by pc494** [comment]
Confirmed, this is a bug.

**Comment by hakonanes** [comment]
How it's done in the supplementary code to the above referenced paper: https://github.com/marcdegraef/3Drotations/blob/4cb7a53cd588de04e0e60c9322f554204a76555c/src/python/rotations.py#L58-L83

**Comment by hakonanes** [comment]
This is handled in #201.
