### ISSUE TITLE
Expand list of related projects in the documentation

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#245]
We should expand the (non-exhaustive) [list of related projects](https://orix.readthedocs.io/en/stable/related_projects.html) with packages users of orix might find useful (add more, or comment below, as more projects come to mind!):
- [x] [DefDap](https://github.com/MechMicroMan/DefDAP)
- [x] [quaternion](https://github.com/moble/quaternion)
- [x] [texture](https://github.com/usnistgov/texture)
- [x] [pymicro](https://github.com/heprom/pymicro/)

**Comment by pc494** [comment]
We should also make an effort to stop accidentally/needlessly duplicating functionality provided elsewhere by stable python packages (maybe that's just my new role talking though!)

**Comment by hakonanes** [comment]
Yes, that is the main motivation for such a list!

**Comment by pc494** [comment]
Yes, maybe more of a reminder for me, as I'm often sloppy in this regard.

**Comment by hakonanes** [comment]
I raised this issue because of a brief discussion of IO readers in https://github.com/MechMicroMan/DefDAP/issues/92.

**Comment by hakonanes** [comment]
This is basically the same as #70.
