### ISSUE TITLE
Preparing for a v0.8 release

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#247]
After inverse pole figure (IPF) functionality (PR 235) is in, I think it is time for a new minor release.

See the [milestone](https://github.com/pyxem/orix/milestone/14) for issues and PRs to close. I closed the v0.7.1 as it seems like we'll skip this release.

I don't know how long it will take, but I hope we can make the release around mid December. What do you think about this @pc494 and @harripj?

**Comment by pc494** [comment]
Final deadline of December 24th? That means it's 100% in for the new year? Would ideally have it all wrapped up the week before (so like, December 17th)

**Comment by hakonanes** [comment]
Sounds good. I'm busy this and next week, but plan to focus on closing the issues and PRs a couple of days before December 17th...

**Comment by pc494** [comment]
Okay, so the next key stage for this is me reviewing (and probably merging some/all of):

- [ ] #253 
- [ ] #252 
- [ ] #234
- [ ] #201

This checklist is to hold me to account. Ideally will have all those in by Friday 17th, then can do a sweep in the earlier part of next week.

**Comment by hakonanes** [comment]
I've got all the bug fixes I want in for v0.8.

**Comment by hakonanes** [comment]
Final bug fix for v0.8 in #260.

**Comment by pc494** [comment]
I think this is all good to go now. Will package up later today.

**Comment by hakonanes** [comment]
Sounds good! I'm very excited to start using the new features in the kikuchipy docs.

**Comment by hakonanes** [comment]
Great work @pc494 and @harripj with the release Phillip just put out!

I'll react later today or tomorrow when the conda-forge bot opens a PR. I don't think there will be any updates necessary, but will of course double check.
