### ISSUE TITLE
Support Rotation.from_axes_angles(axes, angles)

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#250]
We should support `Rotation.from_axes_angles(axes, angles)` as a complement to the current `Rotation.from_neo_euler()`. The reason is that at the moment, initializing a rotation from an axis/angle pair is too much work.

"Minimal" initialization of a rotation from a Euler angle triplet

```python
>>> import numpy as np
>>> from orix.quaternion import Rotation
>>> rot = Rotation.from_euler(np.radians((45, 0, 0)))
>>> rot
Rotation (1,)
[[ 0.9239 -0.     -0.     -0.3827]]
```

From an axis/angle pair (notice the extra two lines: import and axangle initialization)

```python
>>> import numpy as np
>>> from orix.quaternion import Rotation
>>> from orix.vector import AxAngle
>>> axangle = AxAngle.from_axes_angles((0, 0, -1), np.radians(45))
>>> rot = Rotation.from_neo_euler(axangle)
>>> rot
Rotation (1,)
[[ 0.9239  0.      0.     -0.3827]]
```

What we should support

```python
>>> import numpy as np
>>> from orix.quaternion import Rotation
>>> rot = Rotation.from_axes_angles((0, 0, -1), np.radians(45))
>>> rot
Rotation (1,)
[[ 0.9239  0.      0.     -0.3827]]
```

Should we then support `Rotation.from_rodrigues()` and `Rotation.from_homochoric()` as well? I don't see a reason why. We can also still support `Rotation.from_neo_euler()`.

The proposed solution is perhaps less elegant code wise, but *much* simpler to use.

I added this to the v0.8 milestone since it is a very simple addition.

**Comment by harripj** [comment]
I like this idea, I find myself using the second syntax here a lot and it would be more simple to have the third syntax available. A second idea would be `AxAngle().as_rotation()` or similar. But perhaps it is easier to maintain just one instantiation method.

**Comment by pc494** [comment]
Would we just run the extra lines inside the method?

```python
def from_axes_angles(self,ax,angles):
    axangle = AxAngle.from_axes_angles(ax,angles)
    rot = Rotation.from_neo_euler(axangle)
    return rot
```

**Comment by hakonanes** [comment]
> Would we just run the extra lines inside the method?

Yes, I have no desire to add extra computations!

**Comment by hakonanes** [comment]
> A second idea would be `AxAngle().as_rotation()` or similar. But perhaps it is easier to maintain just one instantiation method.

While it can be elegant to support `as_rotation()`, my vote is for just supporting `from_*()` instantiation methods for now.

**Comment by hakonanes** [comment]
FYI, I'll push a PR with a suggestion tomorrow.
