### ISSUE TITLE
Move the misorientation clustering notebook to this repo from the demo repo

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#263]
As @pc494 said in #229, we should replace the [demo repo](https://github.com/pyxem/orix-demos) entirely with [the user guide](https://orix.readthedocs.io/en/stable) built from this repo.

To do this, we need to:
- [x] Move [the misorientation clustering notebook](https://nbviewer.ipython.org/github/pyxem/orix-demos/blob/master/03%20-%20Clustering%20Misorientations.ipynb) to this repo, most likely stored with cell outputs including figures so it displays nicely in the user guide
- [x] Remove any references to the demo repo
- [ ] Archive the demo repo for some months?
- [ ] Delete the demo repo

My view is that the addition of the new notebook to the repo doesn't necessitate a new minor release, and could instead be "released" as a v0.8.1 patch release, so that the notebook becomes part of the "stable" docs.

**Comment by pc494** [comment]
This is patch level, I agree.

In terms of archiving, in the medium term I think we should cull the repo down to a README that says where the demos are and where the data is, version it as 0.8.1 (in orix-demos) archive that and then delete at some much later point.

**Comment by hakonanes** [comment]
The orix-demos repo is now archived.
