### ISSUE TITLE
Release 0.8.1

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#275]
I suggest we make a patch release v0.8.1 after these are in or fixed
- [x] #272 
- [x] #274
- [x] #277
- [x] #278
- [x] #279
- [x] #280
- [x] Release on conda-forge

Changes since 0.8: https://github.com/pyxem/orix/compare/v0.8.0...master

EDIT: Plan to release on Monday Feb. 14.

**Comment by hakonanes** [comment]
No new features in master, so we can tag v0.8.1 directly from master.

**Comment by pc494** [comment]
@hakonanes are you happy to package this one up?

**Comment by hakonanes** [comment]
Yes, I can do that.

**Comment by pc494** [comment]
Great many thanks :D

**Comment by hakonanes** [comment]
Sure! I'm working to fix some old bugs and make some minor improvements to `CrystalMap` to be included. Unless anything else comes up, I'll make a release on Monday.

**Comment by hakonanes** [comment]
Maintainers logged in can now see the draft release for 0.8.1 [here](https://github.com/pyxem/orix/releases): any suggestions for improvements are welcome in this issue.

**Comment by hakonanes** [comment]
I'll publish the 0.8.1 release after checks pass on master. Will follow up conda-forge after publication to PyPI.

**Comment by hakonanes** [comment]
I think updating the v0.8.1 tag locally to point to the new commit on master (after #282 is merged), pushing it to the repo, and re-running the publish action manually should do the trick. Hopefully, the action fetches the updated master, with version set to 0.8.1, and will upload it to PyPI.

**Comment by pc494** [comment]
iirc one can manually delete the dev version on pypi

**Comment by hakonanes** [comment]
> iirc one can manually delete the dev version on pypi

That sounds wonderful.

**Comment by hakonanes** [comment]
Don't think I can do it, as I'm not a listed maintainer of orix on PyPI.

**Comment by hakonanes** [comment]
There we are:
* Release notes (with updated tag): https://github.com/pyxem/orix/releases/tag/v0.8.1
* PyPI: https://pypi.org/project/orix/

**Comment by pc494** [comment]
I have deleted the stray `0.9.dev0` from Pypi, @hakonanes I will add you as a PyPi admin?

**Comment by hakonanes** [comment]
Super! Yes please.

**Comment by hakonanes** [comment]
Published on conda-forge: https://anaconda.org/conda-forge/orix.
