### ISSUE TITLE
0.8.2 patch release

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#286]
I suggest to make a 0.8.2 patch release with at least #285, but #281 can also be included since it includes no API changes, but speed-up of quaternion/vector multiplications.

If people are OK with this, I'll turn it into a release tracking issue.

- [x] #285
- [x] #281
- [x] #287 (fixed in #288)
- [x] #290
- [x] #289
- [x] PyPI
- [x] conda-forge

https://github.com/pyxem/orix/compare/v0.8.1...master

**Comment by harripj** [comment]
It's good for me once we close those issues and people are happy 👍
