### ISSUE TITLE
Possible regression in 0.8.1 for orientation clustering

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#297]
The ["Clustering orientations"](https://orix.readthedocs.io/en/stable/clustering_orientations.html) user guide is built from a notebook with stored cell outputs because it is too memory intensive for the Read the Docs server. The notebook was last run with 0.8.0 by me. I ran it again and noticed a possible regression introduced in [0.8.1](https://orix.readthedocs.io/en/stable/changelog.html#version-0-8-1): some orientations *correctly* assigned the "blue" cluster in 0.8.0 are not assigned a cluster in 0.8.1.

Below are the spatial maps of the clusters, with fewer "blue" cluster points produced with 0.8.1:

0.8.0 | 0.8.1
:--:|:---:
![bilde](https://user-images.githubusercontent.com/12139781/155739327-36965fa7-8485-4a5e-9273-65547f993e16.png)|![bilde](https://user-images.githubusercontent.com/12139781/155739339-e141305f-6618-4953-9ea1-d46dff617cf4.png)

I haven't tracked down the cause, but it might be the change of multiplication order necessary to correct the results from `Orientation.angle_with()`. The data to run the notebook is available via the Google Drive link in the top of the notebook.

This possible regression should have been caught by running the notebooks before releasing 0.8.1. To prevent this in the future, we should
- [x] add note in release guide to run all notebooks and check their output before releasing
- [x] use nbval to run *all* notebooks and check the cell output to the stored outputs (only done for the "Clustering orientations" notebook), for example once a week like [done with kikuchipy](https://github.com/pyxem/kikuchipy/blob/develop/.github/workflows/test_documentation_notebooks.yml)

**Comment by hakonanes** [comment]
This git diff https://github.com/pyxem/orix/pull/295/commits/351550581d4ebdf6276ee29e8bca0a932b5fb35d in #295 shows the difference in cell outputs from 0.8.0 and 0.8.1.

**Comment by harripj** [comment]
This is odd. The extra tests seem like a good idea. It would be a good idea to run the notebooks from the `0.8` and `0.8.1` releases to see if this is the case. If so I think your guess that this regression is due to `angle_with` is a good one, although I think we tidied up `angle_with` in this release.

**Comment by harripj** [comment]
I ran the notebook after two commits: after [524277bd8bc1921a8f67da2953370e9669dac909](https://github.com/pyxem/orix/commit/524277bd8bc1921a8f67da2953370e9669dac909), which was before `dot`, `dot_outer` fix, and after [cdffab6aeca1dc0ddfa12c7b9d5850f715bb2879](https://github.com/pyxem/orix/commit/cdffab6aeca1dc0ddfa12c7b9d5850f715bb2879), which was after the fix. Running the notebooks produced the change, as you thought @hakonanes:

Before fix:
![image](https://user-images.githubusercontent.com/16853829/155844921-9cc228cd-82c2-48de-868a-05a8226ad1a2.png)


After fix:
![image](https://user-images.githubusercontent.com/16853829/155844668-1b8d41c0-4d46-4f29-b041-e6874a34e887.png)

The real question is whether this needs to be changed. Whilst there are more dark pixels, can this be corrected by changing some `DBScan` parameters? In #277 we corrected the misorientation calculation, which is now consistent, so I don't think that this a regression of the code, more that the output looks slightly worse, but again maybe this can be corrected by updating the clustering parameters.

**Comment by harripj** [comment]
In fairness looking at the `AxAngle` projection there is a reasonable argument that some of these datapoints do not belong to the blue cluster.
<img width="205" alt="image" src="https://user-images.githubusercontent.com/16853829/155845440-caac548a-d3db-4d7c-a6cc-82e363815504.png">
<img width="231" alt="image" src="https://user-images.githubusercontent.com/16853829/155845562-e7bc605f-9007-4043-8d28-28acc283003d.png">

**Comment by pc494** [comment]
I agree with all comments about finding the regression. I think that both maps constitute physically reasonable solutions to the problem and the `orix` change that caused the "worsening" of the map was well motivated and correct. 

As such I'm not sure this is a regression we should be concerned by - but the issues it raises with regards to are checking process are important :)

**Comment by hakonanes** [comment]
Thank you both for good input. I'll get the tasks in the top comment done in the near future.

**Comment by hakonanes** [comment]
The tasks mentioned in the top comment are done.
