### ISSUE TITLE
Add logo to README?

### ISSUE THREAD

**Issue by harripj** [pyxem/orix#309]
As orix already has a logo, it would be nice to add it to README? eg. [SciPy](https://github.com/scipy/scipy)

**Comment by pc494** [comment]
I never liked the logo much (although I did make it), but I think adding it to README is probably a good idea (eg. reminds people it exists when they make slides)

**Comment by harripj** [comment]
It reminds me of an IPF colour map in a way, although I don't know if that was the intention when designing it?!

If everyone is okay with it I suggest to add the following to README.rst:
```rst
.. raw:: html

    <p>
      <h1>
        <a href="https://orix.readthedocs.io/en/stable/"><img src="doc/_static/img/orix_logo.png" height="100" height="100" alt="orix logo"/></a>
        orix
      </h1>
    </p>
```

Preview:
![image](https://user-images.githubusercontent.com/16853829/160428412-02053bc5-f87e-4c56-bca2-40e31bcbf81a.png)

Thoughts?

**Comment by hakonanes** [comment]
Merged. Thanks, @harripj!
