### ISSUE TITLE
Issue with black code style checker

### ISSUE THREAD

**Issue by harripj** [pyxem/orix#311]
Looks like an update to the `click` package, a dependency of `black`, has been updated and is causing issues. For now code style checks will fail. Issue is here: https://github.com/psf/black/issues/2964

**Comment by hakonanes** [comment]
Seems like it is already solved? Since the code style check in for example #310 ran without issue now?

**Comment by harripj** [comment]
Yes looks like the `black` devs pushed out a patch quick time. Closing this.
