### ISSUE TITLE
Alignment of crystal axes with cartesian basis

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#319]
I'm currently improving the geometrical simulations in kikuchipy to work for crystals of all point groups. I'm basing it on a new `diffsims.crystallography.ReciprocalLatticeVector` class in diffsims (replacing `ReciprocalLatticePoint`, which only works for cubic crystals), which itself is based on `orix.vector.Miller`. This requires some coordinated changes in all three packages by me.

In doing so, I'm debugging against results from two different crystal axis alignments:
* `x||a*, z||c`, used by Aimo Winkelmann in the supplementary material to the "Which way is up" (2016) EBSD paper ([doi](http://dx.doi.org/10.1016/j.matchar.2016.04.008))
* `x||a, z||c*`, used in EMsoft

Currently in orix, the alignment is hard-coded when operating with lattice vectors. This is done by computing the direct structure matrix (3x3 array of base vectors, transposed) from the lattice parameters retreived from `Phase.structure.lattice` (which is an instance of [`diffpy.structure.Lattice`](https://github.com/diffpy/diffpy.structure/blob/fe4b46badf0a6f4add7ae244478e6a35d040db33/src/diffpy/structure/lattice.py#L53))

https://github.com/pyxem/orix/blob/0516e706a215fbeb366d1811cf690f36f41a4d39/orix/vector/miller.py#L889-L899

This prevented me from debugging against Aimo's examples, so I removed the hard-coding and used `diffpy.structure.Lattice.base` directly. This enables any alignment to be used by setting it via `Phase.structure.lattice.setLatBase(base)`, greatly increasing the flexibility.

The only drawback is that the symmetry operations in orix are hard-coded, assuming `x||a, z||c*` I believe. As long as we state this clearly in the documentation, I think it is OK that it is up to the user to provide the correct lattice base. MTEX computes symmetry operations *after* having decided a basis, thus enabling any alignment to be used with symmetry operations. We could opt for this approach, however I haven't figured out a nice way to do this. Any help here would be appreciated.

What do you think? This ties in directly with "Phase 1" in #249, but I think deserves it's own issue, to be settled here.
___

I've made some convenience functions to create any base or change it, and plot the axes alignments. (a, b, c) are circles, (a*, b*, c*) are crosses, and x || east, z || out of plane.

```python
>>> from diffpy.structure import Lattice, Structure
>>> from orix.crystal_map import Phase
>>> a, b, c, alpha, beta, gamma = 1.7, 1.7, 1.4, 90, 90, 120
>>> base = get_base_from_alignment(a, b, c, alpha, beta, gamma, x="a", z="c*")
>>> lattice = Lattice(base=base)
>>> lattice
Lattice(base=array([[ 1.7       ,  0.        ,  0.        ],
       [-0.85      ,  1.47224319,  0.        ],
       [ 0.        ,  0.        ,  1.4       ]]))
>>> phase = Phase(point_group="321", structure=Structure(lattice=lattice))
>>> phase.plot_crystal_axes(grid=True)
```

![alignment_xa_zc*](https://user-images.githubusercontent.com/12139781/162307962-0143e5d6-86d3-40da-906b-61be1a52ddf6.png)

Continuing on example...

```python
>>> lattice2 = Lattice(a, b, c, alpha, beta, gamma)
>>> lattice2
Lattice(a=1.7, b=1.7, c=1.4, alpha=90, beta=90, gamma=120)
>>> new_base = get_new_base_from_alignment(lattice2.base, x="a*", z="c")  # Used by diffpy.structure...
>>> lattice2.setLatBase(new_base)  # ... so nothing changes
>>> lattice2
Lattice(a=1.7, b=1.7, c=1.4, alpha=90, beta=90, gamma=120)
>>> phase2 = Phase(point_group="321", structure=Structure(lattice=lattice2))
>>> phase2.plot_crystal_axes(grid=True)
```

![alignment_xa*_zc](https://user-images.githubusercontent.com/12139781/162309809-3a5bbf85-134b-4b76-8a93-9f8d9dc15da6.png)

**Comment by harripj** [comment]
> The only drawback is that the symmetry operations in orix are hard-coded, assuming x||a, z||c* I believe. As long as we state this clearly in the documentation, I think it is OK that it is up to the user to provide the correct lattice base. MTEX computes symmetry operations after having decided a basis, thus enabling any alignment to be used with symmetry operations. We could opt for this approach, however I haven't figured out a nice way to do this. Any help here would be appreciated.

I like this idea and I think we should clearly state it. I think we should define any phase such that `x||a` and `z||c*`, it then follows from Rowhenhorst et al. (2015) that `y||cross(z, x)`. Whilst it would be better that the user could define any basis and compute the correct symmetry, for now just specifying this explicitly would be an improvement as you mentioned.

As I understand it, at the moment the default base for `diffpy` does not set `a` to be east:
```python
>>> from diffpy.structure import Lattice, Structure
>>> l = Lattice(1.7, 1.7, 1.4, 90, 90, 120)
>>> l.base
array([[ 1.47224319, -0.85      ,  0.        ],
       [ 0.        ,  1.7       ,  0.        ],
       [ 0.        ,  0.        ,  1.4       ]])
```
but this is performed by the convenience function `get_base_from_alignment` you mentioned? I think this would be a good idea to perform by default, although can you foresee this causing any problems with reference frame alignment later?

**Comment by hakonanes** [comment]
Yes, `diffpy.structure` adopts x||a* and z||c, as seen in the final projections above where a* (red X) aligns east.

OK, let us stick to our hard-coded symmetry operations for now, which means we assume that `Phase.structure.lattice.base` has x||a and z||c*. It is then safe for us to remove the hard-coded structure matrix in orix and use `diffpy.structure.Lattice` functionality directly. The only use of `Lattice` in orix is via `Phase.structure`. As long as we check the alignment and change it accordingly upon initialization of `Phase` or setting of `Phase.structure`, then I think we are good. I'll make `_get_new_base_from_alignment()` a private function which is called in these cases.

If we in the future would like to support other alignments, we have to create symmetry operations dynamically *after* the alignment is defined.

**Comment by hakonanes** [comment]
There's now a user guide explaining this alignment.
