### ISSUE TITLE
Calculate, export and import the Polefigure (PDF) or the Inverse Polefigure (IPDF) 

### ISSUE THREAD

**Issue by tarekiraki** [pyxem/orix#320]
Dear Sir or Madam, 

I am quite new to the orix framework. I've been analyzing orientations with mtex so far. I would like to process orientations either with  Polefigure (PDF) or Inverse Polefigure (IPDF) and test if there is a 'orix-way' to accomplish this.

So I would like to ask, if there is a way with orix to (1) calculate an ODF, (2) calculate the PDF/IPDF (3) export the  PDF/IPDF and (4) import the  PDF/IPDF again. The source code in mtex for this pipeline is listed below.

Thanks for help.
Cheers Tarek

```
% calculate ODF
ebsd = EBSD.load(
	filename_ori_data, CS, 'interface', 'generic', 'ColumnNames', 
	{'x' 'y' 'phi1' 'Phi' 'phi2' 'weights'}, 'Bunge');
oris = ebsd.orientations;
odf = calcDensity(oris, 'halfwidth', 3*degree, 'weights', ebsd.weights);

% calculate Pole Figure
pf_odf = calcPoleFigure(odf, h, 'upper');

% export Pole Figure
export(pf_odf, folder_pf, 3*degree)

% import Pole Figure
pf_import = loadPoleFigure(
	fnames, cs, h, 'interface','generic', 'ColumnNames', 
	{'Polar Angle' 'Azimuth Angle' 'Intensity'}, 'RADIANS');

% calulate ODF based on Pole Figure data
odf_recon = calcODF(pf_import,'silent');

% export odf_recon
export(odf_recon, filename_odf_export)
```

**Comment by hakonanes** [comment]
Hi Tarek,

unfortuantely no, orix cannot compute an orientation distribution function. So far, we only have the possibility to compute discrete pole figures "by hand", for example something like this should compute a <111> pole figure assuming point group symmetry m-3m 

```python
import numpy as np
from orix.crystal_map import Phase
from orix.quaternion Orientation, symmetry
from orix.vector import Miller

# Create orientations
x, y, phi1, Phi, phi2 = np.loadtxt("file.txt", unpack=True)
oris = Orientation.from_euler(np.deg2rad([phi1, Phi, phi2]), symmetry.Oh)

# Create direct lattice vectors
uvw111 = Miller(uvw=[1, 1, 1], phase=Phase(point_group=symmetry.Oh))
uvw111 = uvw111.symmetrise(unique=True)  # Get all symmetrically equivalent vectors

# Express lattice vectors in sample reference frame (applying inverse orientations)
uvw111 = uvw111.reshape(1, uvw111.size)  # Reshapes will be unnecessary in the future
oris = oris.reshape(*ori.shape, 1)
r111 = ~oris * uvw111

# Plot pole figures of both hemispheres 
r111.scatter(hemisphere="both", axes_labels=["Xs", "Ys"])
```

![pf111](https://user-images.githubusercontent.com/12139781/163711285-dd6185e7-d471-486b-a011-a2e3987a5fdb.png)

**Comment by hakonanes** [comment]
At this time, calculating orientation distribution functions from orientation data is outside the scope of this package. Therefore, I'm closing this. Thanks for showing interest in orix and asking the question @tarekiraki!
