### ISSUE TITLE
Plotting tests fail due to unavailable TkAgg backend 

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#327]
All [tests](https://github.com/pyxem/orix/runs/6269218670?check_suite_focus=true) creating plots on Ubuntu with Python 3.9 and 3.10 and on Windows with Python 3.9 fail due to an unavailable `TkAgg` backend. I believe we have to set the plotting backend with `matplotlib.use("Agg")` in every test file. I'll check.

**Comment by hakonanes** [comment]
I'm at a loss for the reason for the failing tests, since all tests pass (1) by adding `matplotlib.use("agg")` to all test files and (2) by removing all setting of the backend in these files. The backend is set in the GitHub Actions YAML file

https://github.com/pyxem/orix/blob/f3d05e342f58b72d8b0864add8d64e3c8cef369f/.github/workflows/build.yml#L30

and perhaps this is the only place this should be set. I'm not sure. But I'll make a PR where all backend setting except for in the YAML file is removed.

**Comment by harripj** [comment]
My suspicion is that this is related to the latest matplotlb release: https://github.com/matplotlib/matplotlib/releases

**Comment by hakonanes** [comment]
I also see that I've set the backend to TkAgg in one test file

https://github.com/pyxem/orix/blob/f3d05e342f58b72d8b0864add8d64e3c8cef369f/orix/tests/plot/test_stereographic_plot.py#L35

This might be related.

**Comment by harripj** [comment]
I can't replicate this on my machine using `matplotlib 3.5.2`, but perhaps we try pinning `matplotlib` to `3.5.1` and rerun actions to see if that helps?

**Comment by harripj** [comment]
> I also see that I've set the backend to TkAgg in one test file
> 
> https://github.com/pyxem/orix/blob/f3d05e342f58b72d8b0864add8d64e3c8cef369f/orix/tests/plot/test_stereographic_plot.py#L35
> 
> This might be related.

Seems like it is `"Agg"` in other files, maybe worth sticking to this?

https://github.com/pyxem/orix/blob/f3d05e342f58b72d8b0864add8d64e3c8cef369f/orix/tests/test_crystal_map.py#L30

**Comment by hakonanes** [comment]
> I can't replicate this on my machine

I cannot either. Although I'm not sure, I believe setting the Matplotlib backend in both the Action YAML file and in the test files leads to some confusion and finally failures. I'm setting up a PR with some minor updates and removal of backend setting after tests pass on my branch.

**Comment by hakonanes** [comment]
Tests pass on master. Thanks for reviewing, @harripj!
