### ISSUE TITLE
Introducing Type Hints to orix

### ISSUE THREAD

**Issue by harripj** [pyxem/orix#338]
As discussed in https://github.com/pyxem/orix/pull/334#discussion_r873158671 with @hakonanes and @din14970 we should gradually introduce type hints into orix. This opens up the possibility to perform type checking at during the development phase and assures that data types are well-defined in the documentation.

Apart from #334 the code base currently uses docstring types, whereas @hakonanes suggested that we migrate towards defining types in the function definitions rather than in the docstrings and I would be happy with this change (see comment above), this would mean that type hinting is used and types are removed from the doctring to avoid type definition duplication.

As this may take some time, I suggest that we aim to convert the code base gradually with completion due in 1.0. If everyone is in agreement then new PRs should use type hinting.

**Comment by pc494** [comment]
I had been the hold out on this for some time, but am happy for this to go ahead.

**Comment by harripj** [comment]
Copying this [comment](https://github.com/pyxem/orix/pull/340#issuecomment-1128775422) here for clarity in the discussion:

> Related to https://github.com/pyxem/orix/issues/338, __annotations__ within the future package was only introduced in Python 3.7, hence the CI Python 3.6 build fails.
>
> __annotations__ are needed for type hints when a class operates with another instance of the class, for example: Vector3d.outer(other: Vector3d). There is likely a lot of this in the code base, so introducing type hints while testing with Python 3.6 will cause problems.

**Comment by pc494** [comment]
Given that Python 3.6 is deprecated we should probably stop testing for it?

**Comment by harripj** [comment]
> Given that Python 3.6 is deprecated we should probably stop testing for it?

This could be an option. Python 3.7 is currently supported for ~another year. https://www.python.org/downloads/

**Comment by hakonanes** [comment]
Glad that you brought this up @harripj. It seems to me like the course of action is to:
1. Make a PR dropping support for Python 3.6
2. Continue with type hints including `__annotations__`

**Comment by harripj** [comment]
Sounds like a good plan to me!

**Comment by hakonanes** [comment]
`__annotations__` can now be used in PRs to `develop`. Note that Python 3.6 is still supported for orix 0.9.x, so any patches have to respect this.

**Comment by hakonanes** [comment]
Relevant comment on type *checking* by @harripj: https://github.com/pyxem/orix/pull/340#discussion_r883537419

**Comment by hakonanes** [comment]
Completed in #378.
