### ISSUE TITLE
`Black` formatting for Jupyter Notebooks

### ISSUE THREAD

**Issue by harripj** [pyxem/orix#349]
There is a `jupyter` option for `black` that will format notebook cells: see the installation section https://pypi.org/project/black/

This would be pretty easy to implement if people are interested and would lead to consistent notebook formatting. We would perhaps have to add some `# fmt: off` comments, but I think that this is an easy trade off to improve the look of the doc notebooks.

What does everyone think?

**Comment by harripj** [comment]
Great! Will make a PR and we can discuss further.

**Comment by hakonanes** [comment]
Done in #350!
