### ISSUE TITLE
Access pole density function results outside of plot

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#351]
This suggestion is a follow up to #340, where we (@harripj and I) discussed introducing functionality to easily access the pole density function (PDF) results (the histogram and bin coordinates, and perhaps some derived values) outside of the plot.

We agreed that a new module `orix.measure` could be introduced for all (or most) quantification functionality in orix.

Any thoughts on this module and approach are very welcome.

**Comment by harripj** [comment]
I think this is a good idea. Currently in #340 the PDF logic is contained within `StereographicPlot.pole_density_function()`, which makes it quite inaccessible outside of the plotting functionality. It would be better move it to a more accessible place as @hakonanes discussed above.

**Comment by harripj** [comment]
Reopened due to previous bad merge #355.

**Comment by hakonanes** [comment]
> We agreed that a new module orix.measure could be introduced for all (or most) quantification functionality in orix.

@pc494, do you have any thoughts on this module? @harripj has introduced this in #362.
