### ISSUE TITLE
Plotting IPF key in matplotlib axes

### ISSUE THREAD

**Issue by maclariz** [pyxem/orix#352]
It is easy to display both maps and IPF keys using the .plot() method.

Maps are also easy to put in matplotlib axes for assembling a nice figure for publication using ax.plot_map(....

It is not so easy to do this for the IPF key as far as I can work out.  At the moment, my work around is to make a figure from the IPF key and then plot that figure in an ax.imshow().  Here is my code:

```python
import io as inout
import cv2

def get_img_from_fig(fig, dpi=180):
    buf = inout.BytesIO()
    fig.savefig(buf, format="png", dpi=dpi)
    buf.seek(0)
    img_arr = np.frombuffer(buf.getvalue(), dtype=np.uint8)
    buf.close()
    img = cv2.imdecode(img_arr, 1)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    return img

IPFkey = plot.IPFColorKeyTSL(pg_HCP).plot(return_figure=True)

ax.imshow(get_img_from_fig(IPFkey, dpi=600))
```

Surely there is a nicer way to do this

Thanks

Ian

**Comment by harripj** [comment]
Hi Ian,

thanks for raising this and sharing your workaround! I have come across this problem too in the past and completely agree that this is not the best behaviour. We should implement a `plot_color_key()` method or similar so users can add axes wherever they like on their figure and also show the IPF colour key on a separate set of axes, to allow for more customisability.

**Comment by harripj** [comment]
@maclariz I have put something together in #353 which allows the IPF colour key to be plotted in a separate set of axes on the same figure. Is this the type of functionality you had in mind? (Please bear in mind that the PR in #353 is currently a draft!)

**Comment by maclariz** [comment]
@harripj I won't get chance to test now as about to have dinner and then do something totally unrelated to science for the evening.  But maybe get a chance to have a play later tomorrow.

**Comment by harripj** [comment]
No rush at all, have a look when you can. I hope you have a good evening! 😄

**Comment by hakonanes** [comment]
Also see #332, where @emichr asked rhis question and I gave an answer.

**Comment by hakonanes** [comment]
Thanks for raising this issue, Ian. That both you and @emichr raised this issue within two weeks shows that this must be made easier.

I've pointed out a couple of improvements in #332 which will make obtaining the IPF color key and including it in a plot easier and more flexible. @harripj started in this direction in #353. I suggest we continue the discussion in #332.

**Comment by harripj** [comment]
Reopened due to previous bad merge #354.
