### ISSUE TITLE
plot_scatter method

### ISSUE THREAD

**Issue by maclariz** [pyxem/orix#364]
Can a plot_scatter method be made so that a scatter plot can be included in a matplotlib composite plot, similar to how the plot_ipf_color_key() was made recently in #352 ?

**Comment by hakonanes** [comment]
Thanks for the suggestion @maclariz. In general, including orix' Matplotlib "projections" in a Matplotlib figure with other projections (image, line plot etc.) can indeed be made easier.

I would like to note that the PR in question, #361, has not been reviewed yet (I have myself very limited time the next couple of weeks), so there is not consensus on the best approach yet.

**Comment by maclariz** [comment]
@harripj this looks like it may work.  I am building a big figure for explaining the relationships between the different laths in an alpha-beta Ti alloy, and the stereograms really show the Burgers transformation very nicely, so would be good to include.

**Comment by harripj** [comment]
@maclariz glad to help! You can combine multiple types of axes in the following way, say, for instance, you don't want all of the axes to be `StereographicPlot`:

```python
from orix.vector import Vector3d
from orix import plot  # needed to register MPL projections
from matplotlib import pyplot as plt
import numpy as np

v = Vector3d(np.random.randn(10_000, 3)).unit

fig = plt.figure(figsize=(10, 5))
ax0 = fig.add_subplot(121)
ax1 = fig.add_subplot(122, projection='stereographic')

x = np.linspace(0, 5)
y = np.cos(x)
ax0.plot(x, y)

ax1.scatter(v, s=2)
```
![image](https://user-images.githubusercontent.com/16853829/172647928-99b40887-1843-48ad-ac47-7ea96bb0f3c0.png)

As @hakonanes said, the projections implemented in orix hook into matplotlib, so can interchanged to make custom figures. Also #361 is not set in stone yet, something to keep in mind if you are relying on the new behaviour implemented there.

**Comment by maclariz** [comment]
Well, further investigation and I'm stumped!

I am plotting real space orientations of specific axes with the following code:

plt.rcParams["axes.grid"] = False
sym = symmetry.Ci
v = Vector3d((1, -1, 0))
ori_beta = ~Timap["Beta Titanium"].orientations
ipfkey = plot.IPFColorKeyTSL(sym, direction=v)
ori_beta.symmetry = ipfkey.symmetry
rgb_z = ipfkey.orientation2color(ori_beta)
ori_beta.scatter("ipf", c=rgb_z, direction=ipfkey.direction)

This works pretty well and shows all possible orientations of the selected axis (without bothering about symmetry reduction - which is important as the alpha can transform along any of these axes).  But how to turn this to a list of vectors that give me the [1,-1,0] directions for plotting in a regular sterogram is not clear to me.

**Comment by harripj** [comment]
When you call `InversePoleFigurePlot.scatter()` it calls:
https://github.com/pyxem/orix/blob/2d18672bd3beccf5b9da78e1f22e944d12870c33/orix/plot/inverse_pole_figure_plot.py#L102-L124

with `Orientation` as input (as is the case in the last line of your snippet), it calls:
https://github.com/pyxem/orix/blob/2d18672bd3beccf5b9da78e1f22e944d12870c33/orix/plot/inverse_pole_figure_plot.py#L224-L225

So for your example, the `Vector3d` in the point group fundamental sector can be calculated as:
```python
v_fs = (ori_beta * v).in_fundamental_sector(sym)
```

**Comment by maclariz** [comment]
@harripj This works!

I am now plotting:

v1 = Vector3d((1, -1, 0))
v2 = Vector3d((1, 1, 0))
v_fs = (ori_beta * v)
v2_fs = (ori_beta * v2)
axg = plt.subplot(gs[2,1], projection='stereographic')
axg.scatter(v_fs, c='g')
axg.scatter(v2_fs, c='c')

I took away the in_fundamental_sector(sym) call to make it do whole stereogram

**Comment by maclariz** [comment]
How do I get this into a nice legend?  I get an extra legend entry - "sa_circle"

**Comment by hakonanes** [comment]
We have an example showing how to compose a Matplotlib figure by combining crystal maps, an inverse pole figure, a pole density function with a colorbar and a pole figure: https://orix.readthedocs.io/en/stable/examples/plotting/subplots.html#sphx-glr-examples-plotting-subplots-py. Therefore, I consider this solved.
