### ISSUE TITLE
Profile (and hopefully improve) the speed of our distance functions

### ISSUE THREAD

**Issue by pc494** [pyxem/orix#37]
At present the two (poorly named) distance functions (`distance_1` and `distance_2`) are somewhat limited by RAM/speed. Enhancing the speed (of the slow function) or refactoring (for memory) would be a very productive use of developers time.

**Comment by pc494** [comment]
One such very soft refactor would be:

(These times are for 100 orientations, which is a pretty tiny number, and for 2 no symmetry systems)

Timer unit: 1e-06 s

Total time: 7.37184 s
File: orix-speed-up.py
Function: _distance_1 at line 8


     8                                           @profile
     9                                           def _distance_1(misorientation, verbose):
    10         1          9.0      9.0      0.0      from itertools import combinations_with_replacement as icombinations
    11         1          1.0      1.0      0.0      s_1, s_2 = misorientation._symmetry
    12         1         48.0     48.0      0.0      distance = np.empty((misorientation.size, misorientation.size))
    13         1         21.0     21.0      0.0      index_pairs = icombinations(range(misorientation.size), 2)
    14         1          1.0      1.0      0.0      if verbose:
    15                                                   from tqdm import tqdm
    16                                                   index_pairs = tqdm(index_pairs, total=misorientation.size ** 2)
    17      5051       4552.0      0.9      0.1      for i, j in index_pairs:
    18      5050      34870.0      6.9      0.5          idxi = np.unravel_index(i, misorientation.shape)
    19      5050      24449.0      4.8      0.3          idxj = np.unravel_index(j, misorientation.shape)
    20      5050     932487.0    184.7     12.6          m_1, m_2 = misorientation[idxi], misorientation[idxj]
    21                                                   mis2orientation = (
    22      5050    5943229.0   1176.9     80.6              s_2.outer(~m_1).outer(s_1).outer(s_1).outer(m_2).outer(s_2)
    23                                                   )
    24                                           
    25      5050      28113.0      5.6      0.4          axis = (0, len(misorientation.shape) + 1, len(misorientation.shape) + 2, -1)
    26      5050     388858.0     77.0      5.3          d = mis2orientation.angle.data.min(axis=axis)
    27      5050      10417.0      2.1      0.1          distance[i, j] = d
    28      5050       4782.0      0.9      0.1          distance[j, i] = d
    29         1          1.0      1.0      0.0      return distance

Total time: 6.40948 s
File: orix-speed-up.py
Function: _distance_1_adapted at line 32

    32                                           @profile
    33                                           def _distance_1_adapted(misorientation, verbose):
    34         1          6.0      6.0      0.0      from itertools import combinations_with_replacement as icombinations
    35         1          1.0      1.0      0.0      s_1, s_2 = misorientation._symmetry
    36         1         73.0     73.0      0.0      distance = np.empty((misorientation.size, misorientation.size))
    37         1         24.0     24.0      0.0      index_pairs = icombinations(range(misorientation.size), 2)
    38         1        196.0    196.0      0.0      s1_outer_s1 = s_1.outer(s_1)
    39         1          1.0      1.0      0.0      if verbose:
    40                                                   from tqdm import tqdm
    41                                                   index_pairs = tqdm(index_pairs, total=misorientation.size ** 2)
    42      5051       4540.0      0.9      0.1      for i, j in index_pairs:
    43      5050      35208.0      7.0      0.5          idxi = np.unravel_index(i, misorientation.shape)
    44      5050      24592.0      4.9      0.4          idxj = np.unravel_index(j, misorientation.shape)
    45      5050     933259.0    184.8     14.6          m_1, m_2 = misorientation[idxi], misorientation[idxj]
    46                                                   mis2orientation = (
    47      5050    4978895.0    985.9     77.7              s_2.outer(~m_1).outer(s1_outer_s1).outer(m_2).outer(s_2)
    48                                                   )
    49                                           
    50      5050      28156.0      5.6      0.4          axis = (0, len(misorientation.shape) + 1, len(misorientation.shape) + 2, -1)
    51      5050     389026.0     77.0      6.1          d = mis2orientation.angle.data.min(axis=axis)
    52      5050      10494.0      2.1      0.2          distance[i, j] = d
    53      5050       5006.0      1.0      0.1          distance[j, i] = d
    54                                                   
    55         1          1.0      1.0      0.0      return distance

**Comment by pc494** [comment]
For comparison, the 2nd (RAM crash method) runs this chunk in `0.03s` (x200 on the "safe" option) - so the correct answer is probably to break data sets down into small chunks and fire them through the RAM heavy method.

**Comment by shogas** [comment]
I have an implementation that does just that. I want to run some numbers on different sizes and symmetries before I push, but splitting into smaller chunks seems to work well. Will try to get it done early this week.

**Comment by pc494** [comment]
That would be great! There isn't a rush on this, as I'm currently scrambling to get pyxem and diffsims released again for March. 

One thing to note (I probably should update the contributing guide to reflect this, but I hadn't anticipated having anyone else involved at this stage!) is that I'm trying to keep orix "minor versions" as stable as possible. Here that will probably mean doing a couple of things that wouldn't feel entirely natural like:

* leaving `_distance_1` in the codebase (ideally with a `DeprecationWarning`)
* Then rerouting for the` distance()` method to always call on `_distance_2` (with another deprecation warning)
* Making the "smaller_chunks" a keyword argument (which won't break calls written with the `0.2.0` implementation)

**Comment by shogas** [comment]
Great that you want to keep the minor versions stable. More projects should do that.

Some questions that could be answered in the contribution guide when you write it. (Should probably be discussed elsewhere)
- Do you consider functions starting with an underscore part of the public API that should be stable?
- Does stable include binary equivalence in the output for a given input?

**Comment by shogas** [comment]
Here are some (delayed) performance measurements. `_distance_3` is the new implementation that replaces `_distance_2` in this PR.
```

# Measurements
Memory usage
Symmetry 1 1
Num ori ->            1          20          50         100         500        1000        2000
_distance_1     0.001MB     0.004MB     0.021MB     0.081MB     2.001MB     8.001MB    32.001MB
_distance_2     0.001MB     0.039MB     0.241MB     0.961MB    24.001MB    96.001MB   384.001MB
_distance_3     0.001MB     0.040MB     0.241MB     0.961MB     2.881MB     8.881MB    32.881MB

Symmetry m-3m m-3m
Num ori ->            1          20          50         100         500        1000        2000
_distance_1   212.337MB   212.340MB   212.357MB   212.417MB   214.337MB   220.337MB   244.337MB
_distance_2     0.185MB    73.735MB   460.841MB  1843.361MB     0.000MB     0.000MB     0.000MB
_distance_3     0.278MB     0.834MB     0.851MB     0.911MB     2.831MB     8.831MB    32.831MB


Execution time
Symmetry 1 1
Num ori ->           1          20          50         100         500        1000        2000
_distance_1     0.002s      0.209s      1.264s      5.163s    126.934s    497.460s   2028.837s
_distance_2     0.002s      0.001s      0.002s      0.006s      0.238s      0.950s      3.887s
_distance_4     0.001s      0.001s      0.002s      0.006s      0.086s      0.307s      1.186s

Symmetry m-3m m-3m
Num ori ->           1          20          50         100         500        1000        2000
_distance_1     1.893s    385.762s   2323.262s   9718.339s       -           -          -
_distance_2     2.502s   1406.800s   8916.628s       -           -           -          -
_distance_4     1.262s    207.101s   1202.382s   4692.976s       -           -          -

```

**Comment by pc494** [comment]
@shogas,

Do you have a sense of what the competing effects are here? Naively I would have expected `distance_2` and `distance_4` to have run at the same speed? 

I assume you're happy that these results suggest that #39 is working from a speed/memory perspective?

**Comment by shogas** [comment]
First, I meant to post this as a reply to the PR, but here is probably fine. Also, `_distance_3` and `_distance_4` is the same above (missed some renaming in the output).

Yes, the new implementation seems to be better in every aspect, assuming it produces the same output. I'll add a comment there with a reference here.

I can think of two reasons `_distance_3` being faster.
- Change from `product` to `combinations_with_replacement` removes some unnecessary repetition .
- Smaller arrays means less overhead of allocation. It seems python/numpy manages to reuse the same memory across loop iterations.

(I'm quite sure the first point is true, symmetries (1, m-3m) and (m-3m, 1) should have the same distance?. My testing gives the same output in both the tests and with some random data)
