### ISSUE TITLE
Selection of data from cluster analysis

### ISSUE THREAD

**Issue by maclariz** [pyxem/orix#375]
Perhaps a silly question, but if you run cluster analysis, get some nice results and split your dataset into a small number of orientations (something that happens for most of my datasets), is there then an easy way to select the raw orientations in each area corresponding to a particular cluster for further analysis?

**Comment by hakonanes** [comment]
Have you looked at [the data selection part](https://orix.readthedocs.io/en/stable/crystal_map.html#Select-and-modify-data-from-criteria) of the crystal map tutorial? Your cluster labels in `DBSCAN.labels_` can be used to obtain a flat boolean mask to get a subset of a `CrystalMap` (or orientations) to extract the relevant orientations

```python
# Either of the below operations
ori = xmap[dbscan.labels_ == 1].orientations
ori = xmap.orientations[dbscan.labels_ == 1]
```

If you've passed only orientations corresponding to one phase to `DBSCAN.fit()`, you could do

```python
ori = xmap["alpha-Ti"][dbscan.labels_ == 1].orientations
```

Your use case is quite common, I think, and something we should show in the documentation.

**Comment by maclariz** [comment]
Thank you @hakonanes .  I will use this.

**Comment by hakonanes** [comment]
Great! Please report back if it didn't work as you expected or you found an alternative solution.

I'm reopening this issue as I want us to remember to include an example showing this in the documentation.

**Comment by maclariz** [comment]
Fine.  I won't be able to do much with this instantly, and I am about to take 2 1/2 weeks annual leave.  But if I could do a slice like this on the data, then this makes constructing pole figures from specific variants with appropriately chosen colours rather easy to do...

**Comment by hakonanes** [comment]
> But if I could do a slice like this on the data, then this makes constructing pole figures from specific variants with appropriately chosen colours rather easy to do

That is exactly the motivation behind the implementation of `CrystalMap.__getitem__()` ([code](https://github.com/pyxem/orix/blob/14639a15a4c66c87891debb8656ef187c3b6e9ea/orix/crystal_map/crystal_map.py#L412-L569), [tutorial](https://orix.readthedocs.io/en/stable/crystal_map.html#Select-and-modify-data-from-criteria)).

**Comment by hakonanes** [comment]
I realize this is covered in the docs already.
