### ISSUE TITLE
New minor release v0.10

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#377]
I suggest to publish a minor v0.10 release, as we have seven new unit vector sampling methods, pole density function calculation, and a convenience method for placing the IPF color key in plots (which one user specifically asked to be released, https://github.com/pyxem/orix/pull/361#issuecomment-1204226197).

Before releasing, I'd like to complete [the v0.10.0 milestone](https://github.com/pyxem/orix/milestone/19), which includes removing deprecated functionality and restructuring the documentation (see #372). I removed this milestone from other issues as there are insufficient resources to handle these now.

I hope to close the milestoned issues next week, so a suggested release date is **Friday September 2**. Please let me know if you want any changes to this plan (should we make a release at all? Do more before releasing? etc.).

**Comment by pc494** [comment]
I think there's enough in the CHANGELOG to justify a release as is, everything else will be a bonus :)

**Comment by hakonanes** [comment]
No, it's waiting for #372 to be briefly reviewed a final time and #335 to be addressed (done quickly after the former PR is merged).

**Comment by hakonanes** [comment]
Thank you for reviewing the two previous PRs, Phillip. After #384 is reviewed and merged, I'll have three more PRs:
1. a final PR to `develop` with preparations for 0.10.0
2. merge `develop` into `main`
3. update `develop` post release

**Comment by hakonanes** [comment]
@maclariz, 0.10.0 can now be installed from PyPI, and will become available from conda-forge tomorrow Friday!

**Comment by hakonanes** [comment]
FYI @maclariz, here are some doc examples showing how to add the IPF color key to a figure with orix 0.10:
- [Subplots example](https://orix.readthedocs.io/en/stable/examples/plotting/subplots.html)
- [Crystal map plotting](https://orix.readthedocs.io/en/stable/tutorials/crystal_map.html#Plotting) (forth figure in the plotting section)

**Comment by maclariz** [comment]
Just installed successfully via pip

**Comment by maclariz** [comment]
Was waiting on this and one other thing (a py4dstem update) for data reanalysis.  I am now going to rerun data with updated py4dstem and then see what the results look like in orix.

**Comment by hakonanes** [comment]
Glad to hear you got it successfully!

> I am now going to rerun data with updated py4dstem and then see what the results look like in orix

Your existing analysis should run fine with orix 0.10 (here's [the changelog](https://orix.readthedocs.io/en/stable/changelog.html#version-0-10-0), with few changes to existing functionality). If it doesn't, please report it in an issue, and make sure to [open a discussion](https://github.com/pyxem/orix/discussions) if you get some ideas which aren't issues.

**Comment by maclariz** [comment]
It should.  The main issue was that the big processing box only had the official last version so could not produce figures with the pole figure keys.  Basically, much of what we need for this student's PhD completion is done in rough versions, so we know everything works.  The fully labelled figures were only possible after this update.  And there was a bug in the indexing to fix (now testing the fix) which will affect the quantitative analysis.  But this is basically just rerunning all the datasets through the updated versions and making final optimised figures for that chapter of his thesis.
