### ISSUE TITLE
Patch release 0.10.1

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#390]
I discovered a bug where indexing/slicing into an already sliced `CrystalMap` assumed the initial shape (`_original_shape`) and not the current shape. I'd like to make a patch release 0.10.1.

It's not according to semantic versioning, but I'd like to add deprecation warnings for all references to properties and parameters refering to the z coordinate of a CrystalMap in 0.10.1 as well, with a plan to remove the "functionality" in 0.11. I made a framework for a 3D crystal map when first writing the `CrystalMap` class, but it is brittle, I don't use it myself (and assume nobody does) and it makes adding functionality to `CrystalMap` unnecessarily challenging.

I plan to fix #380 for 0.10.1 as well.

If there aren't any objections to the release and these changes, I'll open separate PRs for each of the three changes, merge them in turn when they are all ready, and then release.

#### Checklist (added by @pc494)

- [x] #391 
- [x] #392 
- [x] #393 
- [x] #394 
- [ ] #395 (post release)

**Comment by pc494** [comment]
I'm fine with "non-semantic" addition of deprecations in patch releases.

**Comment by hakonanes** [comment]
Thank you, Phillip.

All the four open PRs should go into 0.10.1 after they are reviewed, then. I'll clean up the changelog and bump the release version in #391 once the others are merged onto `main`.

**Comment by pc494** [comment]
Feel free to review request me on the other PRs

**Comment by hakonanes** [comment]
Thanks, I’ve done that now.

**Comment by pc494** [comment]
Are you happy to make the release @hakonanes?

**Comment by hakonanes** [comment]
Yes, thank you for the reviews! I just have to bump the version to 0.10.1.

**Comment by hakonanes** [comment]
0.10.1 is now available on PyPI. I'd like to complete the [release steps](https://github.com/pyxem/orix/blob/develop/RELEASE.rst#post-release-action) for 0.10.1 before yanking 0.10.0 from PyPI.

**Comment by hakonanes** [comment]
0.10.1 is now available from `conda-forge` (for Python >= 3.7 only). So, I'll yank 0.10.0 from PyPI.
