### ISSUE TITLE
Phase.from_cif() test fails in Windows with diffpy.structure 3.0.2

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#403]
diffpy.structure v3.0.2 was released yesterday, and today a test of `Phase.from_cif()` which depends on diffpy.structure fails (https://github.com/pyxem/orix/actions/runs/3242311930/jobs/5315429288#step:9:1).

If it's a bug, we should make an orix v0.10.2 release.

**Comment by hakonanes** [comment]
The test was marked as supposed to fail on Windows, but doesn't anymore (horray!), and hence pytest reports it as failing now.

**Comment by harripj** [comment]
Thought this may be the case!
