### ISSUE TITLE
unique option and multiplicity work not properly

### ISSUE THREAD

**Issue by Martin-Rudolph** [pyxem/orix#404]
Cryst = Phase(point_group='6/mmm', structure=Structure(lattice=Lattice(3.073, 3.073, 10.053, 90, 90, 120)))
Direction = Miller(UVTW = [1, -1, 0, 0], phase=Cryst)

Multi = Direction.multiplicity
print(Multi)

>>Multiplicty:
>>[10]

Direction_Equi, idx = Direction.symmetrise(unique=True, return_index=True)
print(Direction_Equi)

>>Miller (10,), point group 6/mmm, UVTW
>>[[ 1. -1.  0.  0.]
 [ 0.  1. -1.  0.]
 [-1.  0.  1.  0.]
 [-1.  1. -0.  0.]
 [ 0. -1.  1.  0.]
 [ 1. -0. -1.  0.]
 [ 1.  0. -1.  0.]
 [-1.  1.  0.  0.]
 [-1. -0.  1.  0.]
 [ 1. -1. -0.  0.]]

SOME DIRECTIONS APPEAR TO BE DOUBLED IN FACT IT SHOULD ONLY BE 6 DIRECTIONS
-> this seems to be an issue of the rounding -0 and 0 are e.g. -1e-17 or 1e-15. 

I guess values should be roundet to the 10 decimal palce or something like that.

**Comment by hakonanes** [comment]
Hi @Martin-Rudolph,

thank you for reporting this issue! I can reproduce your result with the `develop` version on Ubuntu 22.04 with Python 3.10

```python
>>> import numpy as np
>>> from diffpy.structure import Lattice, Structure
>>> from orix.crystal_map import Phase
>>> from orix.vector import Miller
>>> phase = Phase(point_group="6/mmm", structure=Structure(lattice=Lattice(3.073, 3.073, 10.053, 90, 90, 120))
>>> h = Miller(UVTW=[1, -1, 0, 0], phase=phase)
>>> h.symmetrise(unique=True).size
10
>>> np.unique(h.symmetrise(unique=True).data, axis=0).shape
(10, 3)
>>> np.unique(h.symmetrise(unique=True).data.round(12), axis=0).shape
(10, 3)
>>> np.unique(h.symmetrise(unique=True).data.round(11), axis=0).shape
(6, 3)
```

Seems like rounding to the 11th decimal should be OK, but we [decided on the 12th](https://github.com/pyxem/orix/blob/develop/orix/vector/miller.py#L776) some time back...

I suggest to make a PR to the `main` branch with this example as a test and rounding vectors to the 11th decimal when finding the unique vectors. This fix should be released as a v0.10.2 patch.

Are you interested in making this fix, @Martin-Rudolph?

**Comment by hakonanes** [comment]
The link to `Miller.unique()` in the above example is not the relevant line to fix this particular issue, it's in `Object3d.unique()` ([relevant line](https://github.com/pyxem/orix/blob/develop/orix/base/__init__.py#L195)), which `Miller.symmetrise(unique=True)` uses.

**Comment by Martin-Rudolph** [comment]
Hi hakonanes,

not sure if it is only a rounding issue... I rounded the numpy array (for labeling) to three decimals and still got a -0. This seems to be a strange behavior. 

![Unbenannt](https://user-images.githubusercontent.com/40238484/196288308-44d24234-df2c-493f-8c01-52e4497848f4.PNG)

I was forced to add the subsequent codeline to get rid of this behavior

Direction_Equi_Label[Direction_Equi_Label==-0] = 0

Greetings Martin

**Comment by Martin-Rudolph** [comment]
Hi hakonanes,

not sure if it is only a rounding issue... I rounded the numpy array (for labeling) to three decimals and still got a -0. This seems to be a strange behavior.

![Unbenannt](https://user-images.githubusercontent.com/40238484/196289448-d66d4f18-0b90-47d5-88fe-be9fb9cb3cc4.PNG)

I was forced to add:

Direction_Equi_Label[Direction_Equi_Label==-0] = 0

to get rid of this strange behavior

Greetings Martin

**Comment by hakonanes** [comment]
> But is the -0 an issue? Seems to me the important thing here is to get the correct set of unique vectors, as we achieve by rounding to the 11th decimal instead of the 12th as I showed above?

@Martin-Rudolph, do you have time to consider my question above? I believe I've fixed the bug you report here in #405, which we plan to include in a patch release in the next few days.

**Comment by Martin-Rudolph** [comment]
Dear hakonanes,

thanks for the fast response. I have only time to check something like this only once a week. 

Yes rounding to the 10 decimal place seems to be sufficient. I was worried that numpy.unique will make a difference between 0 and -0 but that this is not the case.

greetings 
Martin

**Comment by hakonanes** [comment]
Thank you for confirming, and again for reporting this issue. I'll close it once #405 is merged.

**Comment by hakonanes** [comment]
orix 0.10.2 is available on PyPI (on conda-forge tomorrow). Thanks a lot for reporting this issue @Martin-Rudolph!
