### ISSUE TITLE
Prepare minor release 0.11.0

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#415]
I'd like to get fixes for the following issues released as a patch soon, early next week if possible:
- [x] #413
- [x] (#427)

Any thoughts on a release, suggestions for other bug fixes etc. are welcome.

**Comment by pc494** [comment]
I'm around to review fixes for the next 10 days or so, just tag me :)

**Comment by hakonanes** [comment]
Considering there are a couple nice unreleased features in the `develop` branch (see https://github.com/pyxem/orix/blob/develop/CHANGELOG.rst), I instead suggest to make a 0.11.0 release. If we get the two open PRs merged (# 414 and 416), I'll make a final PR with release changes.

Any comments on this or help with reviewing are much appreciated.

**Comment by pc494** [comment]
Sounds sensible to me, will drop in on the various PR's to help this go smoothly.

**Comment by hakonanes** [comment]
Thank you for reviewing the PRs I had open, @pc494.

I'll see if I can re-format our docs using the PyData Sphinx Theme similar to the [kikuchipy docs](https://kikuchipy.org/en/latest/index.html) this evening. That shouldn't require too many changes to review. I hope we can release 0.11 after that is done.

**Comment by pc494** [comment]
Great stuff :)

**Comment by pc494** [comment]
commenting to confirm I think this is good to release now.

**Comment by hakonanes** [comment]
Thank you for your review efforts, @pc494!

orix 0.11.0 is available from PyPI. The Zenodo page looks. I anticipate the conda-forge release will be available tomorrow morning.

**Comment by hakonanes** [comment]
It's available on conda-forge. On to the next one!
