### ISSUE TITLE
tarball release name

### ISSUE THREAD

**Issue by MarDiehl** [pyxem/orix#418]
The filename of the tarball is currently `v0.10.2.tar.gz` which is not very descriptive. Would it be possible to change it to `orix-0.10.2.tar.gz`?

I know that most users relying on pip or Anaconda don't have this problem, but as an Arch Linux user (and soon contributor of the orix package) this is a minor annoyance.

Note: I think the name is a GitHub default for releases and I don't even know whether it can be changed.

**Comment by hakonanes** [comment]
Hi @MarDiehl,

the tarball/archive name is taken from the release tag, as far as I can tell. My changes in #419 to the automatic release draft creation renames the next release tag to orix-0.11.0 instead of v0.11.0.

Is this sufficient?

**Comment by MarDiehl** [comment]
@hakonanes
thanks for the quick reply. For the tarball, the solution is nice but, but for the release tag it is a little bit strange to have tags starting with 'orix' in the orix repository.
For me, working with `vXX.YY.ZZ.tar.gz` files is not really a problem, package creation is anyways scripted. It is just a little bit strange to have files with meaningless names.
From my side is is of course ok to change the release tag, but I wouldn't be happy to have release tags like this in my repositories. Maybe there is a way to decouple this. I've seen a lot of software on GitHub with `vXX.YY.ZZ.tar.gz` files but there is certainly also software with more speaking releases.
I would at least suggest to wait, I'll also look around if there is a best practice solution.

**Comment by MarDiehl** [comment]
found this:
https://github.com/go-gitea/gitea/issues/18078

**Comment by MarDiehl** [comment]
There is already a link:
https://github.com/pyxem/orix/archive/v0.10.2/orix-0.10.2.tar.gz

**Comment by hakonanes** [comment]
> There is already a link: https://github.com/pyxem/orix/archive/v0.10.2/orix-0.10.2.tar.gz

Great, thanks, did not know this link existed. I've added it to the installation instructions (under "From source") in #420.
