### ISSUE TITLE
Change docs (Sphinx) theme from Furo to PyData

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#423]
I suggest to change the docs (Sphinx) theme from [Furo](https://pradyunsg.me/furo/) to [PyData](https://pydata-sphinx-theme.readthedocs.io/en/stable/).

I've done this for kikuchipy since I found the docs, especially the API reference, easier to navigate with PyData's theme. Another benefit is that HyperSpy will use this theme after v2 is released. NumPy, SciPy and Matplotlib also base their docs on this theme.

The main difference between Furo and PyData is that PyData uses the top nav bar for sections and the left sidebar for navigation within a section. This might initially seem a bit restrictive, but I've found that docs fit nicely into the following four sections:
* User guide: Getting started (installation guide), Usage (tutorials and examples) and Resources (Bibliography, list of Applications [papers], Open datasets, Related projects, License)
* API reference
* Contributing (guide)
* Changelog

The only thing I don't like going from Furo to PyData is that the default main content section is a little too narrow for my taste. I have to restrict code cells in tutorial notebooks to 77 characters in [kikuchipy's tutorials](https://kikuchipy.org/en/latest/tutorials/pattern_matching.html).

What do you think?

**Comment by pc494** [comment]
PyData is really nice I am, If you want to do this @hakonanes I would be very happy :)

**Comment by hakonanes** [comment]
Great! I'll see if I can have a PR ready this evening so we can use this theme in the v0.11 stable version of the docs.
