### ISSUE TITLE
Chunk size in get_distance_matrix

### ISSUE THREAD

**Issue by maclariz** [pyxem/orix#429]
This is just a wee note that I am finding that setting large chunk sizes is much, much better and faster in get_distance_matrix.  By that I mean using 1000, rather than 20.  Maybe that doesn't work on every computer and not everyone has that much RAM, but I suspect that advising people to try this upwards until it fails would be a good thing and save a lot of computation time.  Also, the github mentions nothing about setting "Lazy=True" which is essential for larger datasets.  

Ian

**Comment by hakonanes** [comment]
Thank you for raising this issue, @maclariz. We've expanded the relevant docstrings to explain these observations in more detail.
