### ISSUE TITLE
Add Pre-commit CI

### ISSUE THREAD

**Issue by CSSFrancis** [pyxem/orix#463]
I think it would be nice to add pre-commit CI to run in `orix`.

It's pretty easy to set up and can be configured to run `isort` as well as `black` on the codebase.  This can either be automatic or by commenting `pre-commit auto fix` on some Pull Request.  I think this greatly reduces the barrier for contributing to a repository as a first time contributor.  While it seems like it should be fairly easy to get pre-commit/ black to work I've run into problems with.

1. Code that is already committed not being caught by pre-commit
2. Version mismatch for `black`
3. Pre-commit only running `black` and not isort and failing silently. 

I feel like I'm fairly proficient at most things but pre-commit and `black` give me lots of headaches when I feel like they shouldn't.  Maybe I'm alone here and everyone else has no problems with this :)

**Comment by hakonanes** [comment]
While initially against this (see https://github.com/pyxem/orix/pull/460#issuecomment-1792685648), you've convinced me.

The current code base is in line with our desired formatting (https://github.com/pyxem/orix/blob/develop/.pre-commit-config.yaml). If we set up a pre-commit fix, it should be configured to recognize this.

I'd like to note that I think all listed problems can be fixed without too much effort (?):
1. Run `black` and commit (either amend the previous commit or make a new one)
2. Install version listed in our pre-commit config (https://github.com/pyxem/orix/blob/develop/.pre-commit-config.yaml)
3. As 1., but run `isort` and commit

What do you think of these manual solutions?

**Comment by harripj** [comment]
Just wanted to add my two cents here for anybody using VS Code. There are two extensions for [black](https://marketplace.visualstudio.com/items?itemName=ms-python.black-formatter) and [isort](https://marketplace.visualstudio.com/items?itemName=ms-python.isort) which can be configured to auto-format on save. Personally I find these extensions very useful when developing as one can focus on the logic and forget about the formatting 😄
