### ISSUE TITLE
New production version, likely 0.12.0

### ISSUE THREAD

**Issue by pc494** [pyxem/orix#471]
With #469 coming in and fixing an important bug with significant downstream (--> diffsims --> pyxem) implication it seems likely we will need a new release of orix. Given what's currently in the changelog this is likely to be a minor release. I'll use this issue to collate what we may (or may not) need to get in before making the release.

#### Tagged PRs in unclear states

#442 
#451
#457 
#460 

#### Milestone issues

#439

# Outline of plan (in planned order of merges)

- [x] #472 
- [x] #469 review, adjust and merge
- [x]  copyright  #473 
- [x] #460 which helps with diffsims a fair bit
- [ ] deps

I think the others can be left for now.

**Comment by pc494** [comment]
For what it's worth, I would be happy to merge #462, deal with the copyright notice and send it to production. The bug being solved by #469 is blocking diffsims and pyxem at the moment.

**Comment by CSSFrancis** [comment]
@pc494 #460 Just needs a review.  I think that one should be good to go.

We should do #472 Just to help us get some of the other things in.  I can help review but can't directly clean up others work.

More smaller releases is good.

**Comment by hakonanes** [comment]
I agree that a swift minor release is good. I'll have a look at the docs.

**Comment by pc494** [comment]
Is it worth putting out a release candidate while we wait for some progress on #475?

**Comment by CSSFrancis** [comment]
@pc494 or @hakonanes  Do you want to make a release?  I can do it as well if you would like.

**Comment by hakonanes** [comment]
If it's OK with you I'd like to do it this evening after looking over the latest changes.

**Comment by pc494** [comment]
> If it's OK with you I'd like to do it this evening after looking over the latest changes.

This works for me :)

**Comment by hakonanes** [comment]
I'll have to look over the docs before release, which I'll do tomorrow evening. Hence, I can make the release then at the earliest.

If you would like to give feedback on the changes, we should wait until Thursday.

**Comment by pc494** [comment]
#478 looks good so far. I could look over changes Thursday morning UK time, would it be okay @hakonanes for you to set stuff up this evening and then (assuming all goes well) make a release on Thursday evening?

**Comment by hakonanes** [comment]
Regarding minimal supported versions (Python 3.7), see https://github.com/pyxem/orix/issues/482.

**Comment by CSSFrancis** [comment]
#483 Should be included as well to support `numpy` 2.0.0

**Comment by hakonanes** [comment]
I've opened #487 to bring all changes since the last release onto the `main` branch for tagging and releasing.

**Comment by hakonanes** [comment]
It's on PyPI: https://pypi.org/project/orix/.

Waiting for conda-forge. This evening or tomorrow morning.

**Comment by hakonanes** [comment]
Other updates:
* Zenodo: https://zenodo.org/records/10966629
* New stable docs: https://orix.readthedocs.io/en/stable/index.html?

**Comment by hakonanes** [comment]
For some unexplicable reason, our build action

https://github.com/pyxem/orix/blob/86202927dedf62fb829c1e9675662f9567f46f1d/.github/workflows/python-publish.yml#L39-L41

created a distribution file with name [orix-0.12.tar.gz](https://pypi.org/project/orix/#files), without the patch number. It has always included that before. The version is listed and interpreted correctly all other places I've looked.

Our [conda-forge feedstock build](https://github.com/conda-forge/orix-feedstock/pull/30) therefore failes, because it looks for orix-0.12.0.tar.gz and can't find it. I had to add a `temporary_version` parameter to the `meta.yaml` script to temporarily point conda-forge to the orix-0.12.tar.gz file. **This must be removed when releasing a new version!**

**Comment by hakonanes** [comment]
It's on conda-forge: https://anaconda.org/conda-forge/orix.
