### ISSUE TITLE
Contributors needs updating.

### ISSUE THREAD

**Issue by pc494** [pyxem/orix#474]
Both @CSSFrancis and @viljarjf are currently not in the [Zenodo](https://github.com/pyxem/orix/blob/develop/.zenodo.json) or the [contributors](https://github.com/pyxem/orix/blob/develop/orix/__init__.py) file. If you could each take the time to add yourself that would be great. 

Please note that correct ordering isn't essential for now as I'll revisit this when we come to release.

**Comment by CSSFrancis** [comment]
Done!
