### ISSUE TITLE
Drop support for Python 3.7

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#482]
I suggest to drop support for Python 3.7.

Reasons:
1. NumPy stopped supporting it 3.5y ago (https://endoflife.date/numpy#python-support)
2. HyperSpy stopped supporting it in December after 2.0 (https://hyperspy.org/hyperspy-doc/current/changes.html#id58)
3. It isn't available for Macs with Silicon chips (https://stackoverflow.com/a/70219965/3228100). I've got such a machine, so I cannot test it (easily).

I'll see if I can get it into the v0.12.0 release if people agree.

**Comment by CSSFrancis** [comment]
@hakonanes +1 for this.  Realistically if `numpy` doesn't support it we can't really either as so much depends on `numpy`.

**Comment by hakonanes** [comment]
Agreed! I'll make a PR tomorrow with necessary changes and see if we can remove or simplify some stuff.

**Comment by pc494** [comment]
Dropping old versions of Python is one my favourite things, go right ahead.
