### ISSUE TITLE
Bugfix release 0.12.1

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#492]
I suggest to make a bugfix release 0.12.1 with #491 as soon as possible (like in a few days). Are maintainers OK with this?

**Comment by hakonanes** [comment]
#491 is now ready for merging onto `main`. This will automatically create a release draft. Publishing this releases 0.12.1 on PyPI 🚀 . See that PR for the changelog.

If people are OK with it, I'd like to make the release tomorrow or Saturday.

**Comment by pc494** [comment]
Also, if you're happy with it could we sneak #493 in?

**Comment by hakonanes** [comment]
Yes, the regression was new in 0.12.0. Good point, I'll update the changelog.

And yes, we should include #493. I've asked @harripj to rebase to `main`. We can merge #491 after that, and we're ready to go.

**Comment by hakonanes** [comment]
It's on PyPI (https://pypi.org/project/orix/0.12.1/) and Zenodo (https://zenodo.org/records/11003937).

**Comment by hakonanes** [comment]
I suggest to make a 0.12.1.post0 release to fix #494 for the stable docs.

**Comment by hakonanes** [comment]
0.12.1 is on Anaconda: https://anaconda.org/conda-forge/orix.

**Comment by hakonanes** [comment]
Docs are now fixed: https://orix.readthedocs.io/en/stable/tutorials/clustering_misorientations.html?.
