### ISSUE TITLE
Working with multiple axis conventions in indexation

### ISSUE THREAD

**Issue by pc494** [pyxem/orix#50]
Specifically, currently the code works with "an orientation as a passive rotation from the crystal reference frame to the specimen reference" (see preprint) while many other adopt the opposite convention (ie - 
"orientation matrix transforms the specimen reference frame into the crystal reference frame") - this should be a fairly simple change to implement.

**Comment by dnjohnstone** [comment]
Discussion from #49 

        Yeah at some point we're going to have to ask users to specify the axis convention in which their data was indexed. I think ideally that would be at load time. Unfortunately I don't think that's very well stored in the data files? So it's going to have to be a user defined input at some point I think.

    It is actually stored in many h5ebsd (not KikuchiPy's, though...), which is discussed in the h5ebsd paper by Jackson et al (https://doi.org/10.1186/2193-9772-3-4). But at least not in the .ang files from TSL, which I'm most familiar with. I think we could do what MTEX does, which is to display a warning if it is not set upon loading, and tell the user how to set it.

**Comment by pc494** [comment]
From an implementation perspective, having an argument/kwarg with default set to `None` called 'convention' on `.from_euler()` seems like a sensible approach. Still checking some sources so that I can be sure the things we implement are what people expect.

**Comment by pc494** [comment]
It is my belief that these two conventions correspond to the direct inverse of one another. Thus I suggest simply inverting the final quaternions produced as a conversion step. @dnjohnstone if you could check that you agree that would be great (I used Equation (1) from the preprint & another read through of the Rowenhorst paper to arrive here).

**Comment by pc494** [comment]
#55 closed this.
