### ISSUE TITLE
Make a minor release 0.13.0

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#503]
The CTF reader in #451 enables many more people to use orix. I suggest to make a minor release when it's in.

Anything else people would like to have in before then? I don't think #501 is pressing enough.

Checklist:
- [x] PyPI
- [x] conda-forge
- [x] Zenodo
- [x] ReadTheDocs updated
- [ ] develop branch updated (new changes on main back into develop, bumped version and new empty "Unreleased" changelog)

**Comment by pc494** [comment]
Releasing often is good and I've nothing else I would want to see put in.

**Comment by pc494** [comment]
@hakonanes should I pick this up myself?

**Comment by hakonanes** [comment]
Thanks for the ping, I'll do it by Tuesday!

**Comment by hakonanes** [comment]
Merging https://github.com/pyxem/orix/pull/511 should release v0.13.0.

**Comment by hakonanes** [comment]
It's on PyPI: https://pypi.org/project/orix/
