### ISSUE TITLE
Numpy 2.0.0 problems

### ISSUE THREAD

**Issue by pc494** [pyxem/orix#506]
This has filtered down from upstream (see https://github.com/pyxem/pyxem/issues/1099). `quaternion` on which we depend is currently (and may not for some time be) compatible with `numpy 2.0.0`. 

It's possible we could drag and drop a sister package in place (see discussion https://github.com/moble/quaternion/issues/229) but I'm acutely aware this project is really short of dev resourcing.

The alternative is that we make ourselves `numpy 1.x`  for now.

**Comment by CSSFrancis** [comment]
@pc494 I'm going to try to make the switch this week when I have the time! (Which I should)

**Comment by hakonanes** [comment]
As I mentioned in #507:

> The dependency on numpy-quaternion is NOT important. We only use it for quaternion-quaternion and quaternion-vector multiplication. Our "old" implementation used Numba, and as far as I can remember, it was only twice as slow.
> If numpy-quaternion becomes a hassle, I'd suggest we make it an optional dependency: use it when available, but fall back to Numba if it's not. What do you think?

**Comment by pc494** [comment]
Sorry @hakonanes I had completely forgotten the #507 discussion when I opened this.

**Comment by hakonanes** [comment]
Nono, you opened this long before my post, I just reposted here to say that we're on it (:

**Comment by hakonanes** [comment]
orix 0.13.1 is now available from PyPI, with numpy-quaternion as an optional dependency.

But whaddayaknow, latest diffpy.structure is not compatible with NumPy 2.0: https://github.com/diffpy/diffpy.structure/issues/68.

So orix is still not compatible with NumPy 2.0.

**Comment by pc494** [comment]
patch to 0.13.2 with a minimum version on `diffpy.structure`?

**Comment by hakonanes** [comment]
After they release a new diffpy.structure release compatible with NumPy 2.0? Yes, that sounds like a plan.

**Comment by hakonanes** [comment]
With #525 and an official release of diffpy.structure v3.2.2 (currently an RC out https://pypi.org/project/diffpy.structure/3.2.2rc0/), orix is compatible with NumPy 2.0 (without numpy-quaternion).

**Comment by hakonanes** [comment]
Now that diffpy.structure v3.2.2 is available on PyPI (https://pypi.org/project/diffpy.structure/) and conda-forge (https://anaconda.org/conda-forge/diffpy.structure), we can release orix v0.13.1 which is fully compatible with NumPy v2.

**Comment by hakonanes** [comment]
v0.13.2 I mean
