### ISSUE TITLE
Make numpy-quaternion an optional dependency

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#514]
I see numpy-quaternion has become a NumPy-2.0-transition-bottleneck downstream for pyxem (https://github.com/pyxem/pyxem/issues/1099). There's discussion of our use of this package in https://github.com/pyxem/orix/issues/506 and https://github.com/pyxem/orix/pull/507.

**I suggest to make numpy-quaternion an optional dependency.**

We use numpy-quaternion for three operations:
* Conjugation: https://github.com/pyxem/orix/blob/688ee4a4202da8a8324b6c5fa2059119b0080a67/orix/quaternion/quaternion.py#L208-L214
* quaternion-quaternion multiplication: https://github.com/pyxem/orix/blob/688ee4a4202da8a8324b6c5fa2059119b0080a67/orix/quaternion/quaternion.py#L222-L225
* quaternion-vector multiplication: https://github.com/pyxem/orix/blob/688ee4a4202da8a8324b6c5fa2059119b0080a67/orix/quaternion/quaternion.py#L226-L233

All places for speed, not for functionality. We had implementations of these things without numpy-quaternion before. We can re-introduce these computations as a fall-back if numpy-quaternion is unavailable.

As an added bonus to this work, I want to make it easier to make dependencies in orix optional. numpy-quaternion is a good place to start.

We can do this fairly quickly. If interest, we can make a v0.13.1 patch release.

**Comment by hakonanes** [comment]
I've gotten one 👍🏻, so I'm going for it

**Comment by CSSFrancis** [comment]
@hakonanes That would be fantastic!  I think @ericpre would also be very happy :)

**Comment by pc494** [comment]
I certainly will be very happy. I assume the speed trade-off is significant, but the documentation can be marked up to reflect that.

**Comment by CSSFrancis** [comment]
> I certainly will be very happy. I assume the speed trade-off is significant, but the documentation can be marked up to reflect that.

I think it's a factor of 2 is what @hakonanes said.  I feel that is pretty minimal, there are other places in `orix` where it would be easier to speed things up if we really needed it.

**Comment by hakonanes** [comment]
Recently released numpy-quaternion 2024.0.2 is compatible with NumPy 2. However, I suggest we keep numpy-quaternion as an optional dependency. Rather, we should try to make *more* dependencies optional!
