### ISSUE TITLE
Skip compatibility with Python 3.8 and 3.9?

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#515]
Do we loose much by skipping Python 3.8 and 3.9 compatibility? If we support 3.10 and 3.11 (with the plan to support 3.12), that is perhaps enough?

If yes, I'll make the necessary changes.

**Comment by pc494** [comment]
I have long held that we are too generous with backwards Python compatibility. Python 3.10 is October 2021 which seems good enough for me, writing in September 2024.

**Comment by CSSFrancis** [comment]
My reasoning is always if numpy says they can't [support](https://numpy.org/neps/nep-0029-deprecation_policy.html#drop-schedule) it can we reasonably say that we support it?

**Comment by hakonanes** [comment]
Seems like our dependencies support Python 3.12. So, I suggest to start testing against 3.12 instead of 3.10.

**Comment by pc494** [comment]
Happy with this, especially as py3.12 is now nearly a year old
