### ISSUE TITLE
Plans for v0.13.1 patch release

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#518]
We plan to make a patch release v0.13.1. The main reason is explained in #514.

What I'd like to include:
- [x] #514
- [x] #515
- [x] #516
- [x] #505 (if easy)

The develop branch is free of new features. We can therefore merge fixes to this branch, merge develop into main, and release.

Post-release actions and checks:
- [x] PyPI
- [x] Stable docs
- [x] orix on conda
- [x] orix-base on conda
- [x] Zenodo

**Comment by hakonanes** [comment]
I'll continue on the Python compatibility this evening.

**Comment by pc494** [comment]
How keen are you on #505 for this patch @hakonanes?

**Comment by hakonanes** [comment]
Quite! I'm working on it as we speak. Will make a PR within the hour.

**Comment by hakonanes** [comment]
After #522 is merged, #523 can be merged and 0.13.1 can be released on PyPI.

**Comment by hakonanes** [comment]
I'll make the release later today if people are OK with it.

**Comment by hakonanes** [comment]
orix is now available from conda-forge:
* https://anaconda.org/conda-forge/orix
* https://anaconda.org/conda-forge/orix-base
