### ISSUE TITLE
Dependencies for orix on conda-forge

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#520]
Now that numpy-quaternion is an optional dependency, which packages should be installed with `conda install orix -c conda-forge`?

I suggest to make an `orix-base` package available, without numpy-quaternion. We will still get it with `orix`. Other optional dependencies should have the same behavior.

This means that downstream packages can choose optional dependencies based on which optional functionality they need from orix.

Other suggestions? Thoughts?

**Comment by pc494** [comment]
+1 

This is consistent with matplotlib's behaviour as far as I am aware.

**Comment by hakonanes** [comment]
Indeed, and for dask.

**Comment by hakonanes** [comment]
* https://anaconda.org/conda-forge/orix
* https://anaconda.org/conda-forge/orix-base
