### ISSUE TITLE
Misorientation/Orientation set_symmetry() docstring examples and code produce different results

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#57]
After #50 (c5daae0bf1b3225b14a7aeac903babf1e0ad34ce), but perhaps also before, I do not get the results from the docstrings examples for `Misorientation.set_symmetry()` and `Orientation.set_symmetry()`:

Docstring:

```python
>>> from orix.quaternion.orientation import Misorientation, Orientation
>>> from orix.quaternion.symmetry import C4, C2
>>> data = np.array([[0.5, 0.5, 0.5, 0.5], [0, 1, 0, 0]])
>>> Misorientation(data).set_symmetry(C4, C2)
Misorientation (2,) 4, 2
[[-0.7071  0.     -0.7071  0.    ]
 [ 0.      0.7071 -0.7071  0.    ]]
>>> Orientation(data).set_symmetry(C4)
Orientation (2,) 4
[[-0.7071  0.     -0.7071  0.    ]
 [ 0.     -0.7071 -0.7071  0.    ]]
```

Actual:

```python
>>> from orix.quaternion.orientation import Misorientation, Orientation
>>> from orix.quaternion.symmetry import C4, C2
>>> data = np.array([[0.5, 0.5, 0.5, 0.5], [0, 1, 0, 0]])
>>> Misorientation(data).set_symmetry(C4, C2)
Misorientation (2,) 4, 2
[[-0.7071  0.7071  0.      0.    ]
 [ 0.      1.      0.      0.    ]]
>>> Orientation(data).set_symmetry(C4)
Orientation (2,) 1, 4
[[-0.7071  0.     -0.7071  0.    ]
 [ 0.      1.      0.      0.    ]]
```

What is wrong, the docstring or the code?

We should also make a `Orientation.__repr__()`, since it is with reference to `C1` and only has one associated symmetry.

**Comment by pc494** [comment]
I think the docstring vs use case have disagreed for a while. My instinct is that the actual solution is "better" - assuming the `C4` has the tetrad axis down `z` we would expect `[0,1,0,0]`, a 90 degree rotation about `x` lies within the fundamental zone, and thus be unchanged. I'll look up/check the misorientation case to confirm.

You're correct about the `__repr__()`, although the current behaviour isn't that far out.

**Comment by dnjohnstone** [comment]
Is the action here that we need to update the docstring examples?
