### ISSUE TITLE
Reader/writer for CrystalMap

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#59]
I want a simple HDF5 reader/writer for the `CrystalMap` class into v0.3 (#58), so we can start to put stuff from pyxem in it, and read the data back into pyxem and kikuchipy.

I like the h5ebsd format specified here: Jackson, M.A., Groeber, M.A., Uchic, M.D. et al. h5ebsd: an archival data format for electron back-scatter diffraction data sets. Integrating Materials 3, 44–55 (2014). https://doi.org/10.1186/2193-9772-3-4. I plan to follow this as closely as it suits our `CrystalMap` class. Will add `manufacturer` and `version` datasets in the top group. This way we can easily create readers into e.g. MTEX's EBSD.load of this format.

Are there any interest in having readers returning anything else than a `CrystalMap`? If not, we should consider having only `orix.load()` figuring out which format the file is in, and returning a `CrystalMap` using the proper reader (like HyperSpy's clever `hs.load()`).

I would like to have the possibility to use the `Phase` and `PhaseList` classes in kikuchipy, not always via a `CrystalMap`. I therefore plan to make the reader/writer modular, so that these two classes are written to more or less standard data groups and sets.

Does anyone have any other requirements for the reader/writer? I'm not familiar with everything pyxem would want to write, so if there are anything that does not fit into a `CrystalMap`, please let me know.

**Comment by pc494** [comment]
I am happy with more or less everything here, although I'm not sure I understand exactly how the 4th paragraph works.

On the final paragraph, I think the plan is to have the `pyxem` to `orix` conversion happen "in memory" so the "pyxem saving" is really just "orix saving"

**Comment by hakonanes** [comment]
What I mean is that we have an HDF5 format (based on h5ebsd) for saving EBSD patterns in kikuchipy (https://kikuchipy.org/en/latest/load_save_patterns.html#h5ebsd, https://github.com/kikuchipy/kikuchipy/blob/master/kikuchipy/io/plugins/h5ebsd.py#L686). We have phase info in EBSD metadata, and write this to the proper HDF5 data group/set. I would like to have orix write these data sets to a kikuchipy h5ebsd file. I basically format the metadata dictionary in a specified way, and let orix write that dictionary to an HDF5 data set in a specified way.

So `pyxem` will create a `CrystalMap`, and then write that to file? I guess that is simplest.

**Comment by dnjohnstone** [comment]
I'm all good with following the h5ebsd format defined by Jackson et al and it would indeed be good to have this in.
