### ISSUE TITLE
Release 0.1.0

### ISSUE THREAD

**Issue by dnjohnstone** [pyxem/orix#7]
We should make a proper pypi and conda release of this package, which needs:

- [x] Continuous integration updated
- [x] Coveralls setup
- [x] Tests packaged within orix
- [x] make license GPL-3
- [x] Github and pypi release
- [ ] conda release

**Comment by dnjohnstone** [comment]
@pc494 elsewhere you'd said something along the lines of "change license" - why do you want to do that? I guess you meant to go from MIT --> GPL-3 but I don't personally see much reason to. Happy to be convinced though.

**Comment by pc494** [comment]
Yes, I was thinking exactly that MIT to GPL-3 change; mainly for consistency reasons. In general I  do also prefer our code being under a GPL-3 license.

**Comment by dnjohnstone** [comment]
conda packaging is failing due to me making a silly mistake leaving our license defined inconsistently in setup.py

This will require a 0.1.1 pypi release to resolve so I'm closing this issue in favour of that.
