### ISSUE TITLE
Implement all qu2eu, qu2om, etc. from Rowenhorst et al. (2015) "Consistent representations..."?

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#79]
When computing with symmetry operations I sometimes want the rotation matrix instead of the quaternion. Should we add some `Quaternion.to_om` etc. as in the [Rowenhorst et al. (2015) paper](https://iopscience.iop.org/article/10.1088/0965-0393/23/8/083501)? If yes, how should the API be? `Quaternion.qu2om()` looks a bit strange, and `Rotation.to_euler()` is already in use... I prefer the above `Quaternion.to_om()`, `Quaternion.to_ax()` etc.

And, is there a reason for `to_euler()` to be a `Rotation` method and not a `Quaternion` method?

**Comment by dnjohnstone** [comment]
Agree that I don't like .qu2om() and personally prefer .to_matrix() which I feel is marginally more self documenting, but I'm not super bothered.

Being a Rotation method feels natural to me though as Quaternions don't only have to be used to represent rotations i.e. it's just one representation of a Rotation (even if it is the essential one in orix).

Do you feel it's more natural as a Quaternion method?

**Comment by hakonanes** [comment]
No, I agree with you, these should be Rotation methods. And to_matrix() is better!

I'll make a PR after we've released v0.3. I plan to return ndarrays where we don't have a class for the format (likr matrix).

**Comment by pc494** [comment]
Just a note: I wrote vectorised versions of a lot of `transforms3d` code for diffsims, code which will be brought over for `v0.4` so maybe hold off on writing anything new on this in the short term. Although consider me another vote for `to_omatrix`

**Comment by hakonanes** [comment]
@pc494, sounds great. Do you know how long after v0.3 is released until you will look at that?

**Comment by pc494** [comment]
> @pc494, sounds great. Do you know how long after v0.3 is released until you will look at that?

Within a month hopefully

**Comment by pc494** [comment]
The stuff I wrote for diffsims isn't going to do matrix conversions, so if that's the first one on the list I would port the implementations from transforms3d: (https://github.com/matthew-brett/transforms3d/blob/master/transforms3d/quaternions.py) for 
`to_matrix` and (maybe) `from_matrix`

**Comment by hakonanes** [comment]
> The stuff I wrote for diffsims isn't going to do matrix conversions, so if that's the first one on the list I would port the implementations from transforms3d: (https://github.com/matthew-brett/transforms3d/blob/master/transforms3d/quaternions.py) for
> `to_matrix` and (maybe) `from_matrix`

Great, I'll set up a PR if thats OK with you.

**Comment by hakonanes** [comment]
For now I'm satisfied that the quaternion <-> orientation matrix conversion is in.

If no one else wants more of these conversion, I will close this for now.

**Comment by pc494** [comment]
Yep, I think putting them in as and when people need them is probably the way to go. Closing.
