### ISSUE TITLE
0.2.4 release

### ISSUE THREAD

**Issue by pc494** [pyxem/orix#80]
I'm going to release a patch version of the `v0.2` series to force matplotlib to be `<3.3`. I've chosen this solution (rather than a backport) as:

a) I think the way we were using the (now deprecated) arguments did serve a specific purpose within the code
b) Supporting the older release cycle (a tiny bit) isn't the worst idea in the world but ...
c) as we want people moving forward we have a bit more flexibility in approach (eg - requiring constraints on other packages)
d) The demos will fail with `v0.2.3` and `matplotlib > 3.2`, and we as developers can easily make the avoidable

**Comment by dnjohnstone** [comment]
Is this necessary since we're literally right on top of a 0.3.0 release?

**Comment by dnjohnstone** [comment]
Meh, if you want to do it - no harm=no foul.  #81 merged

**Comment by pc494** [comment]
The matplotlib change means that the demos (for 0.2 series) would be broken, and I think it might take us a little while to replicate the plotting behaviour (that was for our use case was good imo) in the 0.3 series. In general I would pass up on doing stuff like this to support old versions, but this is the one the pre-print refers to
