### ISSUE TITLE
Sampling SO3

### ISSUE THREAD

**Issue by pc494** [pyxem/orix#95]
This is really two related issues (some previous discussion in #90) 

1) There are lots of ways to grid in SO3, it seems reasonable to add new ones in as kwarg specified routines with `uniform_SO3_sample` - specifically cubochoric seems like a decent idea.

2) Deciding exactly what resolution should mean. In general the problem arises as uniform sampling is equal volume, but most users will want an angle based report. My belief is that the density of points is always given by dividing `N` (number of points) by the "volume" dimensionless of the area covered (`8*pi` for all of SO3). 

Currently we use "resolution" to mean:

The distance from a rotation to 4 of its neighbours. This is because our implementation creates 6 direct neighbours, four of which are a fixed distance apart (ie - independent of where within SO3 we are). The other two neighbours are equidistant but there distance will vary. This is so that:
`
dV = sin beta dalpha dbeta dgamma`

remains constant (using alpha, beta and gamma, left to right as in https://iopscience.iop.org/article/10.1088/0965-0393/23/8/083501/pdf)

So assuming a small change in each angle, near the origin we have

`dV = sin(beta) dalpha dbeta dgamma`

and at some other beta = Beta

`dV = sin(Beta) dBeta dalpha dgamma`

Setting the two equal and dividing through we find:

`dbeta = (sin(Beta)/sin(beta) dBeta`

so this size (in radians) changes. Our currently implementation is such that the average value is the same as `dalpha`, but half the time the two "beta neighbours" will be closer than the characteristic distance and half the time they will be further away.

The alternative is to talk about the "characteristic disorientation", as discussed in https://iopscience.iop.org/article/10.1088/0965-0393/24/8/085013

**Comment by hakonanes** [comment]
Thanks a lot for clarifying @pc494!

1. Will `get_sample_fundamental()` be the function to call for any other sampling routines as well?

2. I just have to square this information with the fact that setting the (volume) "resolution" in the current implementation equal to the (angle) "characteristic disorientation" in the cubochoric sampling leads returns more samples from the former compared to the latter.

**Comment by pc494** [comment]
> Thanks a lot for clarifying @pc494!
> 
> 1. Will `get_sample_fundamental()` be the function to call for any other sampling routines as well?
> 
> 2. I just have to square this information with the fact that setting the (volume) "resolution" 
> in the current implementation equal to the (angle) "characteristic disorientation" in the cubochoric sampling
> leads returns more samples from the former compared to the latter.

1) Yes, with `kwargs` passed through to `uniform_sample_SO3`
2) Think that is to might be as expected, see snippet

```
import numpy as np

num_steps = 100
half_steps = 50
alpha = np.linspace(0, 2 * np.pi, num=num_steps, endpoint=False)
print(alpha[1]-alpha[0])
beta = np.arccos(np.linspace(1, -1, num=half_steps, endpoint=False))
print(np.mean(beta[1:] - beta[:-1])) 
>>> 0.0628...
>>> 0.0583...
```

Meaning that our mean disorientation is  `(4 * 0.0628 + 2 * 0.0583)/6 = 0.612` 

(in degrees those numbers are: 3.60, 3.34 and 3.50)

NB: because rounding (to integer numbers of steps) is pretty essential to the process, I'm not that fussed about "resolution" ambiguities.

**Comment by dnjohnstone** [comment]
Will doing more on this be for `0.4.0` or `future`?

**Comment by hakonanes** [comment]
I would like to get it in for `0.4.0`... I have a naive implementation which needs quite a bit of improvement. I hope to set up a WIP PR within the next couple days.

**Comment by pc494** [comment]
> I would like to get it in for `0.4.0`... I have a naive implementation the cubochoric sampling @pc494 mentions in point 1, which needs quite a bit of improvement. I hope to set up a WIP PR within the next couple days.

if you want me to have a quick parse of what you've got lmk

**Comment by dnjohnstone** [comment]
Is this now closed @pc494 ? Or should it be transferred to a future milestone?

**Comment by pc494** [comment]
@hakonanes wanted to get cubochoric in, but I would be happy to push that to v0.5 ~ I think smaller releases aren't the worst idea.

**Comment by hakonanes** [comment]
> @hakonanes wanted to get cubochoric in, but I would be happy to push that to v0.5 ~ I think smaller releases aren't the worst idea.

Yes, I'm fine with that waiting.

**Comment by dnjohnstone** [comment]
I think the remaining action here is to implement `cubochoric` sampling. Is there any other action? And please could we split them up in to specific issues to assign milestones?

**Comment by pc494** [comment]
> I think the remaining action here is to implement `cubochoric` sampling. Is there any other action? And please could we split them up in to specific issues to assign milestones?

Call this issue 0.4 and then @hakonanes (cubochoric) and I (equal angle) will raise issues for the 0.5 milestone?

**Comment by dnjohnstone** [comment]
> > I think the remaining action here is to implement `cubochoric` sampling. Is there any other action? And please could we split them up in to specific issues to assign milestones?
> 
> Call this issue 0.4 and then @hakonanes (cubochoric) and I (equal angle) will raise issues for the 0.5 milestone?

Good plan, done.
