### ISSUE TITLE
Adding a SpaceGroup object from diffpy.structure to the Phase class

### ISSUE THREAD

**Issue by hakonanes** [pyxem/orix#99]
See initial discussion and motivation in issue #87. I'll submit a WIP PR tomorrow.

Questions:
1. Should we allow initializing a `Phase` only by a point group (and not providing the space group), and setting `Phase.space_group` to `None` by default? Simplest solution is to require the space group, and let the point group always be a derived property.
2. After initialization, should we allow setting the point group, or should this always be derived from the space group? (Difficult if it is `None`.) If allowed, should we set the `Phase.space_group` to `None` if the current space group is not derived from the new point group the user wants to set?
3. What symmetry info should the `__repr__()` method of `Phase`, `PhaseList` and `CrystalMap` show? As it is now they show the point group name. Should we change it to show "symmetry" with both the space group name, and point group name in parantheses? Or just the space group?
4. Should the properties be `point/space_group` or `point/spacegroup`?

I'll only add the `SpaceGroup` object to the `Phase` class, i.e. not extract any of its properties for easier access than via `phase.spacegroup.this_property`. If we want to use the `SpaceGroup.symop_list` (with `SymOp` objects) internally, we can extract the symmetry elements (rotation matrices and translation vectors) like so

```python
>>> from orix.quaternion.rotation import Rotation
>>> from orix.vector import Vector3d
>>> from diffpy.structure.spacegroups import sg35
>>> sg35.short_name
'Cmm2'
>>> Rotation.from_matrix([i.R for i in sg35.symop_list])
Rotation (8,)
[[1.     0.     0.     0.    ]
 [0.     0.     0.     1.    ]
 [0.5774 0.5774 0.     0.5774]
 [0.5774 0.     0.5774 0.5774]
 [1.     0.     0.     0.    ]
 [0.     0.     0.     1.    ]
 [0.5774 0.5774 0.     0.5774]
 [0.5774 0.     0.5774 0.5774]]
>>> Vector3d([i.t for i in sg100.symop_list])
Vector3d (8,)
[[0.  0.  0. ]
 [0.  0.  0. ]
 [0.  0.  0. ]
 [0.  0.  0. ]
 [0.5 0.5 0. ]
 [0.5 0.5 0. ]
 [0.5 0.5 0. ]
 [0.5 0.5 0. ]]
```

**Comment by pc494** [comment]
> Questions:
> 
>1. Should we allow initializing a `Phase` only by a point group (and not providing the space group), 
>and setting `Phase.space_group` to `None` by default? Simplest solution is to require the space group, 
>and let the point group always be a derived property.

Yes, I think there are cases where we could want only the point group. 
> 2. After initialization, should we allow setting the point group, or should this always be derived from the space group? (Difficult if it is `None`.) If allowed, should we set the `Phase.space_group` to `None` if the current space group is not derived from the new point group the user wants to set?

I think that the logic should be:
- if a space group is given the point group comes from that
- if the user choose to set the point group at later point
- case i) if space group is none, set point group (as we could've done earlier, see my answer to 1)
- case ii) if space_group is not none, either (my preference) raise an error or (also fine) raise a warning, set point_group and set space_group to none
> 3. What symmetry info should the `__repr__()` method of `Phase`, `PhaseList` and `CrystalMap` show? 
>  As it is now they show the point group name. 
> Should we change it to show "symmetry" with both the space group name, and point group name in parantheses? 
> Or just the space group?

Both maybe? Given how prevalent point groups are elsewhere in the code. 

>     4. Should the properties be `point/space_group` or `point/spacegroup`?
I prefer the underscore.

**Comment by hakonanes** [comment]
Thanks a lot for those pointers @pc494, really useful as there are so many options for the implementation...

I agree with your proposed logic regarding setting the point group, and the underscore. For the symmetry string representation I'll try to always display both.
